// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameActivityAlertUserConfig = "activity_alert_user_config"

// ActivityAlertUserConfig 告警不再提示配置表
type ActivityAlertUserConfig struct {
	ID         int64 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"id,string"` // 主键
	ActivityID int64 `gorm:"column:activity_id;type:bigint;not null;comment:活动id" json:"activityId"`          // 活动id
	UserID     int64 `gorm:"column:user_id;type:bigint;not null;comment:用户ID" json:"userId"`                  // 用户ID
	CreatedAt  int64 `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                 // 创建时间
}

// TableName ActivityAlertUserConfig's table name
func (*ActivityAlertUserConfig) TableName() string {
	return TableNameActivityAlertUserConfig
}
