// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameActivityCondition = "activity_condition"

// ActivityCondition 活动领取条件-谁能领
type ActivityCondition struct {
	RuleID             int64  `gorm:"column:rule_id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:规则ID，自增主键" json:"ruleId"`          // 规则ID，自增主键
	ActivityID         int64  `gorm:"column:activity_id;type:bigint;not null;comment:活动ID" json:"activityId"`                                     // 活动ID
	ApplicableVipLevel int64  `gorm:"column:applicable_vip_level;type:tinyint;not null;comment:适用VIP等级：0-全部" json:"applicableVipLevel"`           // 适用VIP等级：0-全部
	MaxClaimPerPeriod  int64  `gorm:"column:max_claim_per_period;type:int;not null;comment:可领取次数，0表示不限制" json:"maxClaimPerPeriod"`                // 可领取次数，0表示不限制
	ClaimIntervalUnit  int64  `gorm:"column:claim_interval_unit;type:tinyint;not null;comment:领取次数间隔单位：1-天，2-周，3-月，4-年" json:"claimIntervalUnit"` // 领取次数间隔单位：1-天，2-周，3-月，4-年
	DepositChannels    string `gorm:"column:deposit_channels;type:varchar(100);not null;default:0;comment:关联存款渠道：0-全部" json:"depositChannels"`    // 关联存款渠道：0-全部
	ClaimMethod        int64  `gorm:"column:claim_method;type:tinyint;not null;comment:领取方式，0表示自动领取，1表示手动领取" json:"claimMethod"`                  // 领取方式，0表示自动领取，1表示手动领取
	IsAgentActive      int64  `gorm:"column:is_agent_active;type:int;not null;comment:是否代理线活动，0表示否，1表示是" json:"isAgentActive"`                    // 是否代理线活动，0表示否，1表示是
	SpecificAgents     int64  `gorm:"column:specific_agents;type:tinyint;not null;comment:指定代理线:0表示否，1表示是" json:"specificAgents"`                 // 指定代理线:0表示否，1表示是
	InviteCodes        string `gorm:"column:invite_codes;type:varchar(1000);not null;comment:指定代理邀请码,使用,好分割" json:"inviteCodes"`                  // 指定代理邀请码,使用,好分割
	CreateAt           int64  `gorm:"column:create_at;type:int;not null;comment:创建时间" json:"createAt"`                                            // 创建时间
	UpdateAt           int64  `gorm:"column:update_at;type:int;not null;comment:修改时间" json:"updateAt"`                                            // 修改时间
	OpUser             string `gorm:"column:op_user;type:varchar(32);not null;default:system;comment:操作人" json:"opUser"`                          // 操作人
}

// TableName ActivityCondition's table name
func (*ActivityCondition) TableName() string {
	return TableNameActivityCondition
}
