// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/shopspring/decimal"

const TableNameAgentCommissionDay = "agent_commission_day"

// AgentCommissionDay 代理商每天佣金统计
type AgentCommissionDay struct {
	ID                int64           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id,string"`               // 主键ID
	AgentID           int64           `gorm:"column:agent_id;type:bigint;comment:代理商ID" json:"agentId"`                                        // 代理商ID
	AgentName         string          `gorm:"column:agent_name;type:varchar(255);comment:代理商名称" json:"agentName"`                              // 代理商名称
	AgentLevelID      int64           `gorm:"column:agent_level_id;type:int;comment:代理商等级序号" json:"agentLevelId"`                              // 代理商等级序号
	AgentLevelName    string          `gorm:"column:agent_level_name;type:varchar(50);comment:代理商等级名称" json:"agentLevelName"`                  // 代理商等级名称
	CommissionAmount  decimal.Decimal `gorm:"column:commission_amount;type:decimal(18,2);default:0.00;comment:当天佣金额度" json:"commissionAmount"` // 当天佣金额度
	CommissionYear    int64           `gorm:"column:commission_year;type:int;comment:年" json:"commissionYear"`                                 // 年
	CommissionMonth   int64           `gorm:"column:commission_month;type:int;comment:月" json:"commissionMonth"`                               // 月
	CommissionDay     int64           `gorm:"column:commission_day;type:int;comment:日" json:"commissionDay"`                                   // 日
	LastOperator      string          `gorm:"column:last_operator;type:varchar(100);comment:最后操作人" json:"lastOperator"`                        // 最后操作人
	LastOperationTime int64           `gorm:"column:last_operation_time;type:bigint;comment:最后操作时间" json:"lastOperationTime"`                  // 最后操作时间
	CreateTime        int64           `gorm:"column:create_time;type:bigint;comment:创建时间" json:"createTime"`                                   // 创建时间
}

// TableName AgentCommissionDay's table name
func (*AgentCommissionDay) TableName() string {
	return TableNameAgentCommissionDay
}
