// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbSportsMatchTeamRank = "fb_sports_match_team_rank"

// FbSportsMatchTeamRank 球队排行榜数据表
type FbSportsMatchTeamRank struct {
	ID              int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:球队ID" json:"id,string"` // 球队ID
	LeaguePhase     int64  `gorm:"column:league_phase;type:int;not null;comment:联赛阶段" json:"leaguePhase"`          // 联赛阶段
	LeagueSubphase  int64  `gorm:"column:league_subphase;type:int;not null;comment:联赛子阶段" json:"leagueSubphase"`   // 联赛子阶段
	TeamID          int64  `gorm:"column:team_id;type:int;not null;comment:球队ID" json:"teamId"`                    // 球队ID
	Wins            int64  `gorm:"column:wins;type:int;not null;comment:胜场数" json:"wins"`                          // 胜场数
	Draws           int64  `gorm:"column:draws;type:int;not null;comment:平场数" json:"draws"`                        // 平场数
	Losses          int64  `gorm:"column:losses;type:int;not null;comment:负场数" json:"losses"`                      // 负场数
	GoalsScored     int64  `gorm:"column:goals_scored;type:int;not null;comment:进球数" json:"goalsScored"`           // 进球数
	GoalsAgainst    int64  `gorm:"column:goals_against;type:int;not null;comment:失球数" json:"goalsAgainst"`         // 失球数
	GoalDifference  int64  `gorm:"column:goal_difference;type:int;not null;comment:净胜球" json:"goalDifference"`     // 净胜球
	Points          int64  `gorm:"column:points;type:int;not null;comment:积分" json:"points"`                       // 积分
	TeamLogo        string `gorm:"column:team_logo;type:varchar(255);not null;comment:球队logo路径" json:"teamLogo"`   // 球队logo路径
	TeamName        string `gorm:"column:team_name;type:varchar(255);not null;comment:球队名称" json:"teamName"`       // 球队名称
	GroupThirdPlace int64  `gorm:"column:group_third_place;type:int;comment:小组第三排名" json:"groupThirdPlace"`        // 小组第三排名
	TopicID         int64  `gorm:"column:topic_id;type:int;not null;comment:专题ID" json:"topicId"`                  // 专题ID
	LeagueID        int64  `gorm:"column:league_id;type:int;not null;comment:联赛ID" json:"leagueId"`                // 联赛ID
	LanguageType    string `gorm:"column:language_type;type:varchar(50);comment:语言类型" json:"languageType"`         // 语言类型
	CreatedAt       int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                // 记录创建时间
	UpdatedAt       int64  `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                // 记录更新时间
}

// TableName FbSportsMatchTeamRank's table name
func (*FbSportsMatchTeamRank) TableName() string {
	return TableNameFbSportsMatchTeamRank
}
