// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFbSportsMatch = "fb_sports_match"

// FbSportsMatch 赛事表
type FbSportsMatch struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id,string"`
	FbID          int64     `gorm:"column:fb_id;type:int;not null;comment:赛事ID" json:"fbId"`                                   // 赛事ID
	LanguageType  string    `gorm:"column:languageType;type:varchar(50);comment:语言类型" json:"languageType"`                     // 语言类型
	MatchPlayType int64     `gorm:"column:match_play_type;type:int;comment:赛事分组类型" json:"matchPlayType"`                       // 赛事分组类型
	Nsg           string    `gorm:"column:nsg;type:text;comment:比分列表，提供各个赛事阶段的比分" json:"nsg"`                                  // 比分列表，提供各个赛事阶段的比分
	Mg            string    `gorm:"column:mg;type:text;comment:赔率列表" json:"mg"`                                                // 赔率列表
	Tms           int64     `gorm:"column:tms;type:int;not null;comment:单个赛事玩法总数" json:"tms"`                                  // 单个赛事玩法总数
	Tps           string    `gorm:"column:tps;type:text;comment:盘口组标签集合" json:"tps"`                                           // 盘口组标签集合
	Lg            string    `gorm:"column:lg;type:text;comment:联赛信息" json:"lg"`                                                // 联赛信息
	Ts            string    `gorm:"column:ts;type:text;comment:球队信息，包含主队和客队" json:"ts"`                                        // 球队信息，包含主队和客队
	Mc            string    `gorm:"column:mc;type:text;comment:比赛时钟信息" json:"mc"`                                              // 比赛时钟信息
	Bt            int64     `gorm:"column:bt;type:int;not null;comment:开赛时间" json:"bt"`                                        // 开赛时间
	Ms            int64     `gorm:"column:ms;type:int;not null;comment:赛事进行状态" json:"ms"`                                      // 赛事进行状态
	Fid           int64     `gorm:"column:fid;type:int;not null;comment:赛制的场次、局数、节数" json:"fid"`                               // 赛制的场次、局数、节数
	Fmt           int64     `gorm:"column:fmt;type:int;not null;comment:赛制" json:"fmt"`                                        // 赛制
	Ss            int64     `gorm:"column:ss;type:int;not null;comment:销售状态 1 开售，2 暂停，其他状态都不展示" json:"ss"`                     // 销售状态 1 开售，2 暂停，其他状态都不展示
	Ne            int64     `gorm:"column:ne;type:int;not null;comment:中立场标记 0 非中立场 ，1 中立场" json:"ne"`                         // 中立场标记 0 非中立场 ，1 中立场
	As_           string    `gorm:"column:as;type:text;comment:动画直播地址集合" json:"as"`                                            // 动画直播地址集合
	Sid           int64     `gorm:"column:sid;type:int;not null;comment:运动ID" json:"sid"`                                      // 运动ID
	Ssi           int64     `gorm:"column:ssi;type:int;not null;comment:主/客发球 1主队发球 2客队发球" json:"ssi"`                         // 主/客发球 1主队发球 2客队发球
	Mp            string    `gorm:"column:mp;type:varchar(255);comment:赛事辅助标记，如附加赛、季前赛等" json:"mp"`                            // 赛事辅助标记，如附加赛、季前赛等
	Smt           int64     `gorm:"column:smt;type:int;not null;comment:滚球赛事当前阶段标识：常规时间，加时赛，点球大战等" json:"smt"`                 // 滚球赛事当前阶段标识：常规时间，加时赛，点球大战等
	Ty            int64     `gorm:"column:ty;type:int;not null;comment:赛事类型 1 冠军投注赛事，2 正常赛事 , see enum: match_type" json:"ty"` // 赛事类型 1 冠军投注赛事，2 正常赛事 , see enum: match_type
	Ye            string    `gorm:"column:ye;type:varchar(50);comment:冠军赛事联赛赛季，如：2019年" json:"ye"`                             // 冠军赛事联赛赛季，如：2019年
	Nm            string    `gorm:"column:nm;type:varchar(255);comment:冠军赛赛事名称，用于展示" json:"nm"`                                // 冠军赛赛事名称，用于展示
	Sb            string    `gorm:"column:sb;type:text;comment:比分板" json:"sb"`                                                 // 比分板
	Pl            int64     `gorm:"column:pl;type:int;not null;comment:是否可以开售滚球盘口 0 否，1 是" json:"pl"`                          // 是否可以开售滚球盘口 0 否，1 是
	CreatedAt     time.Time `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                           // 创建时间
	UpdatedAt     time.Time `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                           // 更新时间
}

// TableName FbSportsMatch's table name
func (*FbSportsMatch) TableName() string {
	return TableNameFbSportsMatch
}
