// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/shopspring/decimal"

const TableNameFbSportsMatchRecommendPlayOptions = "fb_sports_match_recommend_play_options"

// FbSportsMatchRecommendPlayOptions 玩法推荐选项表
type FbSportsMatchRecommendPlayOptions struct {
	ID                int64           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增ID" json:"id,string"`                     // 自增ID
	MarketID          int64           `gorm:"column:market_id;type:bigint;not null;comment:玩法ID" json:"marketId"`                                    // 玩法ID
	RecommendReason   string          `gorm:"column:recommend_reason;type:varchar(255);comment:推荐原因" json:"recommendReason"`                         // 推荐原因
	MarketGroupName   string          `gorm:"column:market_group_name;type:varchar(255);not null;comment:盘口组名" json:"marketGroupName"`               // 盘口组名
	SaleStatus        int64           `gorm:"column:sale_status;type:tinyint;not null;comment:玩法销售状态，0暂停，1开售，-1未开售" json:"saleStatus"`               // 玩法销售状态，0暂停，1开售，-1未开售
	IsParlaySupported int64           `gorm:"column:is_parlay_supported;type:tinyint;not null;comment:是否支持串关，0 不可串关，1 可串关" json:"isParlaySupported"` // 是否支持串关，0 不可串关，1 可串关
	IsBestLine        int64           `gorm:"column:is_best_line;type:int;comment:是否为最优线，带线玩法可用该字段进行排序，从小到大" json:"isBestLine"`                      // 是否为最优线，带线玩法可用该字段进行排序，从小到大
	LineValue         string          `gorm:"column:line_value;type:varchar(50);comment:line值，带线玩法的线，例如大小球2.5线" json:"lineValue"`                    // line值，带线玩法的线，例如大小球2.5线
	MarketType        int64           `gorm:"column:market_type;type:int;not null;comment:玩法类型，如亚盘、大小球等" json:"marketType"`                          // 玩法类型，如亚盘、大小球等
	OptionFullName    string          `gorm:"column:option_full_name;type:varchar(255);not null;comment:选项全称，投注框一般用全称展示" json:"optionFullName"`      // 选项全称，投注框一般用全称展示
	OptionShortName   string          `gorm:"column:option_short_name;type:varchar(255);not null;comment:选项简称(全名or简名)" json:"optionShortName"`       // 选项简称(全名or简名)
	TeamID            int64           `gorm:"column:team_id;type:bigint;comment:球员玩法球队ID" json:"teamId"`                                             // 球员玩法球队ID
	OptionType        int64           `gorm:"column:option_type;type:int;not null;comment:选项类型，主、客、大、小等" json:"optionType"`                          // 选项类型，主、客、大、小等
	EuropeanOdds      decimal.Decimal `gorm:"column:european_odds;type:decimal(10,3);not null;comment:欧盘赔率，赔率小于0代表锁盘" json:"europeanOdds"`           // 欧盘赔率，赔率小于0代表锁盘
	BaseOdds          decimal.Decimal `gorm:"column:base_odds;type:decimal(10,3);comment:赔率，根据请求参数返回对应类型赔率" json:"baseOdds"`                         // 赔率，根据请求参数返回对应类型赔率
	OddsFormatType    int64           `gorm:"column:odds_format_type;type:int;not null;comment:赔率类型" json:"oddsFormatType"`                          // 赔率类型
	OutcomeResult     int64           `gorm:"column:outcome_result;type:int;comment:选项结算结果，仅虚拟体育展示" json:"outcomeResult"`                            // 选项结算结果，仅虚拟体育展示
	LegacyLine        string          `gorm:"column:legacy_line;type:varchar(50);comment:带线玩法的线，老版本兼容字段" json:"legacyLine"`                          // 带线玩法的线，老版本兼容字段
	CreatedAt         int64           `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                                       // 创建时间
	UpdatedAt         int64           `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                                       // 更新时间
}

// TableName FbSportsMatchRecommendPlayOptions's table name
func (*FbSportsMatchRecommendPlayOptions) TableName() string {
	return TableNameFbSportsMatchRecommendPlayOptions
}
