// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGameOperationUrl = "game_operation_url"

// GameOperationUrl 游戏运营内链配置
type GameOperationUrl struct {
	ID             int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id,string"`
	Language       string `gorm:"column:language;type:varchar(100);not null;default:en;comment:语言" json:"language"` // 语言
	LeagueName     string `gorm:"column:league_name;type:varchar(100);not null;comment:联赛名称" json:"leagueName"`     // 联赛名称
	MatchTime      int64  `gorm:"column:match_time;type:int;not null;comment:比赛时间" json:"matchTime"`                // 比赛时间
	HomeName       string `gorm:"column:home_name;type:varchar(100);comment:主队名称" json:"homeName"`                  // 主队名称
	HomeIcon       string `gorm:"column:home_icon;type:varchar(255);comment:主队图标" json:"homeIcon"`                  // 主队图标
	VisitorName    string `gorm:"column:visitor_name;type:varchar(100);comment:客队名称" json:"visitorName"`            // 客队名称
	VisitorIcon    string `gorm:"column:visitor_icon;type:varchar(255);comment:客队图标" json:"visitorIcon"`            // 客队图标
	GameProviderID int64  `gorm:"column:game_provider_id;type:int;not null;comment:游戏平台id" json:"gameProviderId"`   // 游戏平台id
	MatchID        string `gorm:"column:match_id;type:varchar(100);not null;comment:比赛id" json:"matchId"`           // 比赛id
	LeagueID       string `gorm:"column:league_id;type:varchar(100);not null;comment:联赛id" json:"leagueId"`         // 联赛id
	Status         int64  `gorm:"column:status;type:tinyint;not null;comment:状态: 1-启用 0-停用" json:"status"`          // 状态: 1-启用 0-停用
	CreatedAt      int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                  // 创建时间
	UpdatedAt      int64  `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                  // 更新时间
	CreatedBy      string `gorm:"column:created_by;type:varchar(30);comment:操作人姓名" json:"createdBy"`                // 操作人姓名
	UpdatedBy      string `gorm:"column:updated_by;type:varchar(30);comment:最后更新人" json:"updatedBy"`                // 最后更新人
}

// TableName GameOperationUrl's table name
func (*GameOperationUrl) TableName() string {
	return TableNameGameOperationUrl
}
