// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLiveGame = "live_game"

// LiveGame 直播赛事表
type LiveGame struct {
	ID             int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:直播ID" json:"id,string"`        // 直播ID
	MatchType      int64  `gorm:"column:match_type;type:tinyint;comment:赛事类型(1=足球，3=篮球)" json:"matchType"`                  // 赛事类型(1=足球，3=篮球)
	MatchID        int64  `gorm:"column:match_id;type:bigint;comment:赛事ID" json:"matchId"`                                  // 赛事ID
	MatchName      string `gorm:"column:match_name;type:varchar(255);comment:赛事名称" json:"matchName"`                        // 赛事名称
	MatchNameEn    string `gorm:"column:match_name_en;type:varchar(255);comment:赛事名称(英文)" json:"matchNameEn"`               // 赛事名称(英文)
	LeagueID       int64  `gorm:"column:league_id;type:bigint;comment:联赛ID" json:"leagueId"`                                // 联赛ID
	LeagueName     string `gorm:"column:league_name;type:varchar(255);comment:联赛名称" json:"leagueName"`                      // 联赛名称
	LeagueNameEn   string `gorm:"column:league_name_en;type:varchar(255);comment:联赛名称(英文)" json:"leagueNameEn"`             // 联赛名称(英文)
	CoverImage     string `gorm:"column:cover_image;type:varchar(255);comment:封面图片" json:"coverImage"`                      // 封面图片
	HomeTeam       string `gorm:"column:home_team;type:varchar(255);not null;comment:主队名称" json:"homeTeam"`                 // 主队名称
	HomeTeamEn     string `gorm:"column:home_team_en;type:varchar(255);comment:主队名称(英文)" json:"homeTeamEn"`                 // 主队名称(英文)
	AwayTeam       string `gorm:"column:away_team;type:varchar(255);not null;comment:客队名称" json:"awayTeam"`                 // 客队名称
	AwayTeamEn     string `gorm:"column:away_team_en;type:varchar(255);comment:客队名称(英文)" json:"awayTeamEn"`                 // 客队名称(英文)
	MatchStatus    int64  `gorm:"column:match_status;type:tinyint;comment:赛事状态（1=未开赛，3=结束，5=其他）" json:"matchStatus"`        // 赛事状态（1=未开赛，3=结束，5=其他）
	StartTime      int64  `gorm:"column:start_time;type:bigint;not null;comment:赛事开始时间" json:"startTime"`                   // 赛事开始时间
	EndTime        int64  `gorm:"column:end_time;type:bigint;not null;comment:赛事结束时间" json:"endTime"`                       // 赛事结束时间
	HomeScore      string `gorm:"column:home_score;type:json;comment:主队各节得分，格式如 [1,0,0,2]" json:"homeScore"`                // 主队各节得分，格式如 [1,0,0,2]
	AwayScore      string `gorm:"column:away_score;type:json;comment:客队各节得分，格式如 [2,0,0,0]" json:"awayScore"`                // 客队各节得分，格式如 [2,0,0,0]
	HomeLogo       string `gorm:"column:home_logo;type:varchar(255);comment:主队LOGO" json:"homeLogo"`                        // 主队LOGO
	AwayLogo       string `gorm:"column:away_logo;type:varchar(255);comment:客队LOGO" json:"awayLogo"`                        // 客队LOGO
	LiveStatus     int64  `gorm:"column:live_status;type:tinyint;comment:直播状态(1=未开始，3=直播中，5=已结束, 7=回放中)" json:"liveStatus"` // 直播状态(1=未开始，3=直播中，5=已结束, 7=回放中)
	PushURL        string `gorm:"column:push_url;type:varchar(355);comment:推流地址" json:"pushUrl"`                            // 推流地址
	PlayURL        string `gorm:"column:play_url;type:varchar(355);comment:播放地址" json:"playUrl"`                            // 播放地址
	LiveAppName    string `gorm:"column:live_app_name;type:varchar(255);comment:推流APP名称" json:"liveAppName"`                // 推流APP名称
	LiveStreamName string `gorm:"column:live_stream_name;type:varchar(255);comment:推流的名称" json:"liveStreamName"`            // 推流的名称
	Position       int64  `gorm:"column:position;type:int;comment:排序号" json:"position"`                                     // 排序号
	CreatedAt      int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                          // 创建时间
	CreatedBy      string `gorm:"column:created_by;type:varchar(255);not null;comment:创建人姓名" json:"createdBy"`              // 创建人姓名
	UpdatedAt      int64  `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                          // 更新时间
	UpdatedBy      string `gorm:"column:updated_by;type:varchar(255);not null;comment:更新人姓名" json:"updatedBy"`              // 更新人姓名
	IsDeleted      int64  `gorm:"column:is_deleted;type:tinyint;default:1;comment:是否删除(1=否，3=是)" json:"isDeleted"`          // 是否删除(1=否，3=是)
}

// TableName LiveGame's table name
func (*LiveGame) TableName() string {
	return TableNameLiveGame
}
