// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePointsRewards = "points_rewards"

// PointsRewards 积分商城奖励配置
type PointsRewards struct {
	ID          int64  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	Language    string `gorm:"column:language;type:varchar(100);not null;comment:语言包" json:"language"`          // 语言包
	Name        string `gorm:"column:name;type:varchar(255);not null;comment:奖励物品名称" json:"name"`               // 奖励物品名称
	Integral    int64  `gorm:"column:integral;type:int;not null;comment:奖励领取所需积分" json:"integral"`              // 奖励领取所需积分
	GoldCoins   int64  `gorm:"column:gold_coins;type:int;not null;comment:金币" json:"goldCoins"`                 // 金币
	Image       string `gorm:"column:image;type:varchar(255);not null;comment:图片" json:"image"`                 // 图片
	Status      int64  `gorm:"column:status;type:tinyint(1);not null;comment:状态: 1=开启,2=禁用" json:"status"`      // 状态: 1=开启,2=禁用
	CreatedAt   int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                 // 创建时间
	UpdatedAt   int64  `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                 // 更新时间
	UpdatedUser string `gorm:"column:updated_user;type:varchar(255);not null;comment:最后修改人" json:"updatedUser"` // 最后修改人
}

// TableName PointsRewards's table name
func (*PointsRewards) TableName() string {
	return TableNamePointsRewards
}
