// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTDoingRedPacketRainTask = "t_doing_red_packet_rain_task"

// TDoingRedPacketRainTask 红包雨推送任务表
type TDoingRedPacketRainTask struct {
	ID           int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	ActivityCode string `gorm:"column:activity_code;type:varchar(64);not null;comment:活动唯一标识" json:"activityCode"`                  // 活动唯一标识
	DoingID      int64  `gorm:"column:doing_id;type:bigint unsigned;not null;comment:活动配置ID" json:"doingId"`                        // 活动配置ID
	UID          int64  `gorm:"column:uid;type:bigint unsigned;not null;comment:用户ID" json:"uid"`                                   // 用户ID
	Username     string `gorm:"column:username;type:varchar(64);not null;comment:用户名" json:"username"`                              // 用户名
	Currency     string `gorm:"column:currency;type:varchar(16);not null;comment:币种" json:"currency"`                               // 币种
	TriggerType  string `gorm:"column:trigger_type;type:varchar(32);not null;comment:触发类型:login_no_deposit" json:"triggerType"`     // 触发类型:login_no_deposit
	LoginAt      int64  `gorm:"column:login_at;type:bigint;not null;comment:登录时间" json:"loginAt"`                                   // 登录时间
	ScheduledAt  int64  `gorm:"column:scheduled_at;type:bigint;not null;comment:计划推送时间" json:"scheduledAt"`                         // 计划推送时间
	PushedAt     int64  `gorm:"column:pushed_at;type:bigint;not null;comment:实际推送时间" json:"pushedAt"`                               // 实际推送时间
	PushStatus   int64  `gorm:"column:push_status;type:tinyint;not null;default:1;comment:推送状态:1待推送2已推送3已取消4已过期" json:"pushStatus"` // 推送状态:1待推送2已推送3已取消4已过期
	CancelReason string `gorm:"column:cancel_reason;type:varchar(255);not null;comment:取消原因" json:"cancelReason"`                   // 取消原因
	CreatedAt    int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt    int64  `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
}

// TableName TDoingRedPacketRainTask's table name
func (*TDoingRedPacketRainTask) TableName() string {
	return TableNameTDoingRedPacketRainTask
}
