// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/shopspring/decimal"

const TableNameWinLuckyUserDailyStat = "win_lucky_user_daily_stat"

// WinLuckyUserDailyStat Lucky 用户每日统计表
type WinLuckyUserDailyStat struct {
	ID           int64           `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id,string"`     // 主键ID
	DrawConfigID int64           `gorm:"column:draw_config_id;type:bigint unsigned;not null;comment:活动主配置ID" json:"drawConfigId"`        // 活动主配置ID
	DrawDate     string          `gorm:"column:draw_date;type:varchar(16);not null;comment:统计日期 YYYY-MM-DD" json:"drawDate"`             // 统计日期 YYYY-MM-DD
	UID          int64           `gorm:"column:uid;type:bigint unsigned;not null;comment:用户ID" json:"uid"`                               // 用户ID
	Username     string          `gorm:"column:username;type:varchar(64);not null;comment:用户名" json:"username"`                          // 用户名
	Currency     string          `gorm:"column:currency;type:varchar(10);not null;comment:币种" json:"currency"`                           // 币种
	RiskFlag     int64           `gorm:"column:risk_flag;type:tinyint;not null;comment:风控标记 0正常 1可疑" json:"riskFlag"`                    // 风控标记 0正常 1可疑
	BetCount     int64           `gorm:"column:bet_count;type:int;not null;comment:下注次数" json:"betCount"`                                // 下注次数
	BetAmount    decimal.Decimal `gorm:"column:bet_amount;type:decimal(20,4);not null;default:0.0000;comment:下注总额" json:"betAmount"`     // 下注总额
	WinCount     int64           `gorm:"column:win_count;type:int;not null;comment:中奖次数" json:"winCount"`                                // 中奖次数
	WinAmount    decimal.Decimal `gorm:"column:win_amount;type:decimal(20,4);not null;default:0.0000;comment:中奖总额" json:"winAmount"`     // 中奖总额
	ClaimCount   int64           `gorm:"column:claim_count;type:int;not null;comment:领取次数" json:"claimCount"`                            // 领取次数
	ClaimAmount  decimal.Decimal `gorm:"column:claim_amount;type:decimal(20,4);not null;default:0.0000;comment:领取总额" json:"claimAmount"` // 领取总额
	LastBetAt    int64           `gorm:"column:last_bet_at;type:bigint;not null;comment:最后下注时间" json:"lastBetAt"`                        // 最后下注时间
	LastWinAt    int64           `gorm:"column:last_win_at;type:bigint;not null;comment:最后中奖时间" json:"lastWinAt"`                        // 最后中奖时间
	LastClaimAt  int64           `gorm:"column:last_claim_at;type:bigint;not null;comment:最后领取时间" json:"lastClaimAt"`                    // 最后领取时间
	CreatedAt    int64           `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                                // 创建时间
	UpdatedAt    int64           `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                                // 更新时间
}

// TableName WinLuckyUserDailyStat's table name
func (*WinLuckyUserDailyStat) TableName() string {
	return TableNameWinLuckyUserDailyStat
}
