// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

const TableNameWinAgentDailyStatistics = "win_agent_daily_statistics"

// WinAgentDailyStatistics 代理每日统计数据表（区分USDT和EGP）
type WinAgentDailyStatistics struct {
	ID                      int64           `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:自增主键" json:"id,string"`                                               // 自增主键
	StatDate                time.Time       `gorm:"column:stat_date;type:date;not null;comment:统计日期（格式：YYYY-MM-DD）" json:"statDate"`                                                          // 统计日期（格式：YYYY-MM-DD）
	StatDateTime            int64           `gorm:"column:stat_date_time;type:bigint;comment:统计日期 时间戳" json:"statDateTime"`                                                                   // 统计日期 时间戳
	AgentUID                int64           `gorm:"column:agent_uid;type:bigint unsigned;not null;comment:代理UID" json:"agentUid"`                                                             // 代理UID
	AgentName               string          `gorm:"column:agent_name;type:varchar(100);not null;comment:代理名称" json:"agentName"`                                                               // 代理名称
	RegisterCount           int64           `gorm:"column:register_count;type:int unsigned;comment:注册人数 - 当天通过该代理链接注册的用户数" json:"registerCount"`                                              // 注册人数 - 当天通过该代理链接注册的用户数
	LoginAppCount           int64           `gorm:"column:login_app_count;type:int unsigned;comment:登录APP人数 - 当天登录过APP的去重用户数" json:"loginAppCount"`                                           // 登录APP人数 - 当天登录过APP的去重用户数
	InstallCount            int64           `gorm:"column:install_count;type:int unsigned;comment:安装人数 - 通过归因平台统计的App安装数量" json:"installCount"`                                               // 安装人数 - 通过归因平台统计的App安装数量
	PlayedGameCount         int64           `gorm:"column:played_game_count;type:int unsigned;comment:有玩游戏记录人数 - 存在投注记录的去重用户数" json:"playedGameCount"`                                        // 有玩游戏记录人数 - 存在投注记录的去重用户数
	NotPlayedGameCount      int64           `gorm:"column:not_played_game_count;type:int unsigned;comment:未玩游戏人数 - 已注册且登录过，但无投注记录的用户数" json:"notPlayedGameCount"`                             // 未玩游戏人数 - 已注册且登录过，但无投注记录的用户数
	TotalBetAmountUsdt      decimal.Decimal `gorm:"column:total_bet_amount_usdt;type:decimal(20,2) unsigned;default:0.00;comment:总投注金额(USDT) - 用户所有有效投注金额总和" json:"totalBetAmountUsdt"`       // 总投注金额(USDT) - 用户所有有效投注金额总和
	TotalBetAmountEgp       decimal.Decimal `gorm:"column:total_bet_amount_egp;type:decimal(20,2) unsigned;default:0.00;comment:总投注金额(EGP) - 用户所有有效投注金额总和" json:"totalBetAmountEgp"`          // 总投注金额(EGP) - 用户所有有效投注金额总和
	TotalBetPeople          int64           `gorm:"column:total_bet_people;type:int unsigned;comment:总投注人数 - 发生投注行为的去重用户数" json:"totalBetPeople"`                                             // 总投注人数 - 发生投注行为的去重用户数
	TotalBetCount           int64           `gorm:"column:total_bet_count;type:int unsigned;comment:总投注笔数 - 用户投注订单总数" json:"totalBetCount"`                                                   // 总投注笔数 - 用户投注订单总数
	FirstRechargeCount      int64           `gorm:"column:first_recharge_count;type:int unsigned;comment:首充人数 - 当天完成首次充值的用户数" json:"firstRechargeCount"`                                      // 首充人数 - 当天完成首次充值的用户数
	FirstRechargeTimes      int64           `gorm:"column:first_recharge_times;type:int unsigned;comment:首充次数 - 首充订单数（通常等于首充人数）" json:"firstRechargeTimes"`                                   // 首充次数 - 首充订单数（通常等于首充人数）
	DailyRechargeCount      int64           `gorm:"column:daily_recharge_count;type:int unsigned;comment:当天充值人数 - 当天充值成功的去重用户数" json:"dailyRechargeCount"`                                    // 当天充值人数 - 当天充值成功的去重用户数
	DailyRechargeTimes      int64           `gorm:"column:daily_recharge_times;type:int unsigned;comment:当天充值次数 - 当天充值成功的订单总数" json:"dailyRechargeTimes"`                                     // 当天充值次数 - 当天充值成功的订单总数
	TotalRechargeAmountUsdt decimal.Decimal `gorm:"column:total_recharge_amount_usdt;type:decimal(20,2) unsigned;default:0.00;comment:当天总充值金额(USDT)" json:"totalRechargeAmountUsdt"`          // 当天总充值金额(USDT)
	TotalRechargeAmountEgp  decimal.Decimal `gorm:"column:total_recharge_amount_egp;type:decimal(20,2) unsigned;default:0.00;comment:当天总充值金额(EGP)" json:"totalRechargeAmountEgp"`             // 当天总充值金额(EGP)
	RepurchaseCount         int64           `gorm:"column:repurchase_count;type:int unsigned;comment:复购人数 - 当天有2次及以上付费的用户数（去重）" json:"repurchaseCount"`                                       // 复购人数 - 当天有2次及以上付费的用户数（去重）
	RepurchaseRate          decimal.Decimal `gorm:"column:repurchase_rate;type:decimal(10,4);default:0.0000;comment:复购率 = 复购人数 / 当天充值人数（去重）" json:"repurchaseRate"`                           // 复购率 = 复购人数 / 当天充值人数（去重）
	WithdrawPeopleCount     int64           `gorm:"column:withdraw_people_count;type:int unsigned;comment:提款人数 - 成功发起并完成提现的去重用户数" json:"withdrawPeopleCount"`                                 // 提款人数 - 成功发起并完成提现的去重用户数
	WithdrawOrderCount      int64           `gorm:"column:withdraw_order_count;type:int unsigned;comment:提款笔数 - 成功提现订单数量" json:"withdrawOrderCount"`                                          // 提款笔数 - 成功提现订单数量
	TotalWithdrawAmountUsdt decimal.Decimal `gorm:"column:total_withdraw_amount_usdt;type:decimal(20,2) unsigned;default:0.00;comment:提现总金额(USDT)" json:"totalWithdrawAmountUsdt"`            // 提现总金额(USDT)
	TotalWithdrawAmountEgp  decimal.Decimal `gorm:"column:total_withdraw_amount_egp;type:decimal(20,2) unsigned;default:0.00;comment:提现总金额(EGP)" json:"totalWithdrawAmountEgp"`               // 提现总金额(EGP)
	WithdrawRateUsdt        decimal.Decimal `gorm:"column:withdraw_rate_usdt;type:decimal(10,4);default:0.0000;comment:提现率(USDT) = 提款总金额(USDT) / 充值总金额(USDT)" json:"withdrawRateUsdt"`        // 提现率(USDT) = 提款总金额(USDT) / 充值总金额(USDT)
	WithdrawRateEgp         decimal.Decimal `gorm:"column:withdraw_rate_egp;type:decimal(10,4);default:0.0000;comment:提现率(EGP) = 提款总金额(EGP) / 充值总金额(EGP)" json:"withdrawRateEgp"`             // 提现率(EGP) = 提款总金额(EGP) / 充值总金额(EGP)
	TotalBonusUsdt          decimal.Decimal `gorm:"column:total_bonus_usdt;type:decimal(20,2) unsigned;default:0.00;comment:累计奖金(USDT) - 注册赠金+充值赠送金额等" json:"totalBonusUsdt"`                 // 累计奖金(USDT) - 注册赠金+充值赠送金额等
	TotalBonusEgp           decimal.Decimal `gorm:"column:total_bonus_egp;type:decimal(20,2) unsigned;default:0.00;comment:累计奖金(EGP) - 注册赠金+充值赠送金额等" json:"totalBonusEgp"`                    // 累计奖金(EGP) - 注册赠金+充值赠送金额等
	ArppuUsdt               decimal.Decimal `gorm:"column:arppu_usdt;type:decimal(10,2) unsigned;default:0.00;comment:平均付费金额(USDT) = 总充值金额(USDT) / 充值人数" json:"arppuUsdt"`                    // 平均付费金额(USDT) = 总充值金额(USDT) / 充值人数
	ArppuEgp                decimal.Decimal `gorm:"column:arppu_egp;type:decimal(10,2) unsigned;default:0.00;comment:平均付费金额(EGP) = 总充值金额(EGP) / 充值人数" json:"arppuEgp"`                        // 平均付费金额(EGP) = 总充值金额(EGP) / 充值人数
	GgrUsdt                 decimal.Decimal `gorm:"column:ggr_usdt;type:decimal(20,2);default:0.00;comment:公司盈亏(USDT) = 用户总投注额(USDT) - 用户总派奖金额(USDT)" json:"ggrUsdt"`                         // 公司盈亏(USDT) = 用户总投注额(USDT) - 用户总派奖金额(USDT)
	GgrEgp                  decimal.Decimal `gorm:"column:ggr_egp;type:decimal(20,2);default:0.00;comment:公司盈亏(EGP) = 用户总投注额(EGP) - 用户总派奖金额(EGP)" json:"ggrEgp"`                              // 公司盈亏(EGP) = 用户总投注额(EGP) - 用户总派奖金额(EGP)
	NgrUsdt                 decimal.Decimal `gorm:"column:ngr_usdt;type:decimal(20,2);default:0.00;comment:公司净盈亏(USDT) = GGR(USDT) - 奖金成本(USDT) - 渠道成本(USDT) - 支付手续费(USDT)" json:"ngrUsdt"`   // 公司净盈亏(USDT) = GGR(USDT) - 奖金成本(USDT) - 渠道成本(USDT) - 支付手续费(USDT)
	NgrEgp                  decimal.Decimal `gorm:"column:ngr_egp;type:decimal(20,2);default:0.00;comment:公司净盈亏(EGP) = GGR(EGP) - 奖金成本(EGP) - 渠道成本(EGP) - 支付手续费(EGP)" json:"ngrEgp"`          // 公司净盈亏(EGP) = GGR(EGP) - 奖金成本(EGP) - 渠道成本(EGP) - 支付手续费(EGP)
	RegisterRechargeRate    decimal.Decimal `gorm:"column:register_recharge_rate;type:decimal(10,4);default:0.0000;comment:注册充值率 = 首充人数 / 注册人数" json:"registerRechargeRate"`                  // 注册充值率 = 首充人数 / 注册人数
	TotalPayoutAmountUsdt   decimal.Decimal `gorm:"column:total_payout_amount_usdt;type:decimal(20,2) unsigned;default:0.00;comment:用户总派奖金额(USDT) - 用户中奖/派彩总金额" json:"totalPayoutAmountUsdt"` // 用户总派奖金额(USDT) - 用户中奖/派彩总金额
	TotalPayoutAmountEgp    decimal.Decimal `gorm:"column:total_payout_amount_egp;type:decimal(20,2) unsigned;default:0.00;comment:用户总派奖金额(EGP) - 用户中奖/派彩总金额" json:"totalPayoutAmountEgp"`    // 用户总派奖金额(EGP) - 用户中奖/派彩总金额
	CreatedAt               time.Time       `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                                                                          // 创建时间
	UpdatedAt               time.Time       `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                                                                          // 更新时间
}

// TableName WinAgentDailyStatistics's table name
func (*WinAgentDailyStatistics) TableName() string {
	return TableNameWinAgentDailyStatistics
}
