// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinLuckyPushTemplate = "win_lucky_push_template"

// WinLuckyPushTemplate Lucky 推送模板平铺配置表
type WinLuckyPushTemplate struct {
	ID                int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	DrawConfigID      int64  `gorm:"column:draw_config_id;type:bigint unsigned;not null;comment:活动主配置ID" json:"drawConfigId"`                     // 活动主配置ID
	TemplateGroupCode string `gorm:"column:template_group_code;type:varchar(64);not null;default:default;comment:模板组编码" json:"templateGroupCode"` // 模板组编码
	TemplateType      string `gorm:"column:template_type;type:varchar(64);not null;comment:模板类型" json:"templateType"`                             // 模板类型
	Lang              string `gorm:"column:lang;type:varchar(16);not null;default:en;comment:语言" json:"lang"`                                     // 语言
	Currency          string `gorm:"column:currency;type:varchar(10);not null;comment:币种，空表示通用" json:"currency"`                                  // 币种，空表示通用
	Title             string `gorm:"column:title;type:varchar(255);not null;comment:标题" json:"title"`                                             // 标题
	Content           string `gorm:"column:content;type:text;comment:内容" json:"content"`                                                          // 内容
	ButtonText        string `gorm:"column:button_text;type:varchar(64);not null;comment:按钮文案" json:"buttonText"`                                 // 按钮文案
	ButtonLink        string `gorm:"column:button_link;type:varchar(500);not null;comment:按钮链接" json:"buttonLink"`                                // 按钮链接
	PopupTitle        string `gorm:"column:popup_title;type:varchar(255);not null;comment:弹窗标题" json:"popupTitle"`                                // 弹窗标题
	PopupContent      string `gorm:"column:popup_content;type:varchar(500);not null;comment:弹窗内容" json:"popupContent"`                            // 弹窗内容
	ContentType       int64  `gorm:"column:content_type;type:tinyint;not null;default:1;comment:1纯文本 2富文本 3占位模板" json:"contentType"`              // 1纯文本 2富文本 3占位模板
	PushChannel       string `gorm:"column:push_channel;type:varchar(32);not null;default:notice;comment:notice/ws/mail" json:"pushChannel"`      // notice/ws/mail
	MailScene         string `gorm:"column:mail_scene;type:varchar(64);not null;comment:消息场景" json:"mailScene"`                                   // 消息场景
	RateLimitKey      string `gorm:"column:rate_limit_key;type:varchar(64);not null;comment:限流键" json:"rateLimitKey"`                             // 限流键
	IsDefault         int64  `gorm:"column:is_default;type:tinyint;not null;comment:是否默认模板" json:"isDefault"`                                     // 是否默认模板
	Sort              int64  `gorm:"column:sort;type:int;not null;comment:排序" json:"sort"`                                                        // 排序
	Status            int64  `gorm:"column:status;type:tinyint;not null;default:1;comment:状态" json:"status"`                                      // 状态
	OperatorName      string `gorm:"column:operator_name;type:varchar(64);not null;comment:操作人" json:"operatorName"`                              // 操作人
	Remark            string `gorm:"column:remark;type:varchar(255);not null;comment:备注" json:"remark"`                                           // 备注
	CreatedAt         int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt         int64  `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
}

// TableName WinLuckyPushTemplate's table name
func (*WinLuckyPushTemplate) TableName() string {
	return TableNameWinLuckyPushTemplate
}
