// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinLuckyConfigHistory = "win_lucky_config_history"

// WinLuckyConfigHistory Lucky 配置历史表
type WinLuckyConfigHistory struct {
	ID           int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id,string"`      // 主键ID
	ConfigID     int64  `gorm:"column:config_id;type:bigint unsigned;not null;comment:配置ID" json:"configId"`                     // 配置ID
	ConfigType   string `gorm:"column:config_type;type:varchar(32);not null;comment:配置类型 main/prize/template" json:"configType"` // 配置类型 main/prize/template
	RefID        int64  `gorm:"column:ref_id;type:bigint unsigned;not null;comment:关联ID" json:"refId"`                           // 关联ID
	VersionNo    int64  `gorm:"column:version_no;type:bigint;not null;comment:版本号" json:"versionNo"`                             // 版本号
	SnapshotJSON string `gorm:"column:snapshot_json;type:json;comment:配置快照JSON" json:"snapshotJson"`                             // 配置快照JSON
	OperatorName string `gorm:"column:operator_name;type:varchar(64);not null;comment:操作人" json:"operatorName"`                  // 操作人
	ChangeReason string `gorm:"column:change_reason;type:varchar(255);not null;comment:变更原因" json:"changeReason"`                // 变更原因
	CreatedAt    int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                                 // 创建时间
}

// TableName WinLuckyConfigHistory's table name
func (*WinLuckyConfigHistory) TableName() string {
	return TableNameWinLuckyConfigHistory
}
