// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gzorm/commons/zorm/model"
)

func newFbSportsMatchMarketGroupSelection(db *gorm.DB, opts ...gen.DOOption) fbSportsMatchMarketGroupSelection {
	_fbSportsMatchMarketGroupSelection := fbSportsMatchMarketGroupSelection{}

	_fbSportsMatchMarketGroupSelection.fbSportsMatchMarketGroupSelectionDo.UseDB(db, opts...)
	_fbSportsMatchMarketGroupSelection.fbSportsMatchMarketGroupSelectionDo.UseModel(&model.FbSportsMatchMarketGroupSelection{})

	tableName := _fbSportsMatchMarketGroupSelection.fbSportsMatchMarketGroupSelectionDo.TableName()
	_fbSportsMatchMarketGroupSelection.ALL = field.NewAsterisk(tableName)
	_fbSportsMatchMarketGroupSelection.ID = field.NewInt64(tableName, "id")
	_fbSportsMatchMarketGroupSelection.MatchID = field.NewInt64(tableName, "match_id")
	_fbSportsMatchMarketGroupSelection.MarketID = field.NewInt64(tableName, "market_id")
	_fbSportsMatchMarketGroupSelection.SelectionNameFull = field.NewString(tableName, "selection_name_full")
	_fbSportsMatchMarketGroupSelection.SelectionNameShort = field.NewString(tableName, "selection_name_short")
	_fbSportsMatchMarketGroupSelection.TeamID = field.NewInt64(tableName, "team_id")
	_fbSportsMatchMarketGroupSelection.SelectionType = field.NewInt64(tableName, "selection_type")
	_fbSportsMatchMarketGroupSelection.OddsEuropean = field.NewField(tableName, "odds_european")
	_fbSportsMatchMarketGroupSelection.Odds = field.NewField(tableName, "odds")
	_fbSportsMatchMarketGroupSelection.OddsType = field.NewInt64(tableName, "odds_type")
	_fbSportsMatchMarketGroupSelection.Outcome = field.NewInt64(tableName, "outcome")
	_fbSportsMatchMarketGroupSelection.LineOld = field.NewString(tableName, "line_old")
	_fbSportsMatchMarketGroupSelection.MarketSaleStatus = field.NewInt64(tableName, "market_sale_status")
	_fbSportsMatchMarketGroupSelection.IsAccumulator = field.NewInt64(tableName, "is_accumulator")
	_fbSportsMatchMarketGroupSelection.IsBestLine = field.NewInt64(tableName, "is_best_line")
	_fbSportsMatchMarketGroupSelection.LineValue = field.NewString(tableName, "line_value")
	_fbSportsMatchMarketGroupSelection.CreatedAt = field.NewInt64(tableName, "created_at")
	_fbSportsMatchMarketGroupSelection.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_fbSportsMatchMarketGroupSelection.fillFieldMap()

	return _fbSportsMatchMarketGroupSelection
}

// fbSportsMatchMarketGroupSelection 赛事盘口玩法选项表
type fbSportsMatchMarketGroupSelection struct {
	fbSportsMatchMarketGroupSelectionDo

	ALL                field.Asterisk
	ID                 field.Int64  // 主键ID
	MatchID            field.Int64  // 赛事ID
	MarketID           field.Int64  // 玩法ID，关联到具体的玩法
	SelectionNameFull  field.String // 选项全称，投注框一般用全称展示
	SelectionNameShort field.String // 选项简称(全名or简名，订单相关为全名，否则为简名)
	TeamID             field.Int64  // 球员玩法球队ID
	SelectionType      field.Int64  // 选项类型，主、客、大、小等，投注时需要提交该字段作为选中的选项参数
	OddsEuropean       field.Field  // 欧盘赔率，目前我们只提供欧洲盘赔率，投注时请提交该字段赔率值作为选项赔率，赔率小于0代表锁盘
	Odds               field.Field  // 赔率，根据请求参数返回对应类型赔率
	OddsType           field.Int64  // 赔率类型
	Outcome            field.Int64  // 选项结算结果，仅虚拟体育展示
	LineOld            field.String // 带线玩法的线，老版本兼容字段，可忽略。如大小球 大 2.5 中的 2.5
	MarketSaleStatus   field.Int64  // 玩法销售状态，0暂停，1开售，-1未开售（未开售状态一般是不展示的）
	IsAccumulator      field.Int64  // 是否支持串关，0 不可串关，1 可串关
	IsBestLine         field.Int64  // 是否为最优线，带线玩法可用该字段进行排序，从小到大
	LineValue          field.String // line值，带线玩法的线，例如大小球2.5线，部分玩法展示可用该字段进行分组展示
	CreatedAt          field.Int64  // 创建时间
	UpdatedAt          field.Int64  // 更新时间

	fieldMap map[string]field.Expr
}

func (f fbSportsMatchMarketGroupSelection) Table(newTableName string) *fbSportsMatchMarketGroupSelection {
	f.fbSportsMatchMarketGroupSelectionDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fbSportsMatchMarketGroupSelection) As(alias string) *fbSportsMatchMarketGroupSelection {
	f.fbSportsMatchMarketGroupSelectionDo.DO = *(f.fbSportsMatchMarketGroupSelectionDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fbSportsMatchMarketGroupSelection) updateTableName(table string) *fbSportsMatchMarketGroupSelection {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.MatchID = field.NewInt64(table, "match_id")
	f.MarketID = field.NewInt64(table, "market_id")
	f.SelectionNameFull = field.NewString(table, "selection_name_full")
	f.SelectionNameShort = field.NewString(table, "selection_name_short")
	f.TeamID = field.NewInt64(table, "team_id")
	f.SelectionType = field.NewInt64(table, "selection_type")
	f.OddsEuropean = field.NewField(table, "odds_european")
	f.Odds = field.NewField(table, "odds")
	f.OddsType = field.NewInt64(table, "odds_type")
	f.Outcome = field.NewInt64(table, "outcome")
	f.LineOld = field.NewString(table, "line_old")
	f.MarketSaleStatus = field.NewInt64(table, "market_sale_status")
	f.IsAccumulator = field.NewInt64(table, "is_accumulator")
	f.IsBestLine = field.NewInt64(table, "is_best_line")
	f.LineValue = field.NewString(table, "line_value")
	f.CreatedAt = field.NewInt64(table, "created_at")
	f.UpdatedAt = field.NewInt64(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *fbSportsMatchMarketGroupSelection) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fbSportsMatchMarketGroupSelection) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 18)
	f.fieldMap["id"] = f.ID
	f.fieldMap["match_id"] = f.MatchID
	f.fieldMap["market_id"] = f.MarketID
	f.fieldMap["selection_name_full"] = f.SelectionNameFull
	f.fieldMap["selection_name_short"] = f.SelectionNameShort
	f.fieldMap["team_id"] = f.TeamID
	f.fieldMap["selection_type"] = f.SelectionType
	f.fieldMap["odds_european"] = f.OddsEuropean
	f.fieldMap["odds"] = f.Odds
	f.fieldMap["odds_type"] = f.OddsType
	f.fieldMap["outcome"] = f.Outcome
	f.fieldMap["line_old"] = f.LineOld
	f.fieldMap["market_sale_status"] = f.MarketSaleStatus
	f.fieldMap["is_accumulator"] = f.IsAccumulator
	f.fieldMap["is_best_line"] = f.IsBestLine
	f.fieldMap["line_value"] = f.LineValue
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f fbSportsMatchMarketGroupSelection) clone(db *gorm.DB) fbSportsMatchMarketGroupSelection {
	f.fbSportsMatchMarketGroupSelectionDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fbSportsMatchMarketGroupSelection) replaceDB(db *gorm.DB) fbSportsMatchMarketGroupSelection {
	f.fbSportsMatchMarketGroupSelectionDo.ReplaceDB(db)
	return f
}

type fbSportsMatchMarketGroupSelectionDo struct{ gen.DO }

type IFbSportsMatchMarketGroupSelectionDo interface {
	gen.SubQuery
	Debug() IFbSportsMatchMarketGroupSelectionDo
	WithContext(ctx context.Context) IFbSportsMatchMarketGroupSelectionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFbSportsMatchMarketGroupSelectionDo
	WriteDB() IFbSportsMatchMarketGroupSelectionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFbSportsMatchMarketGroupSelectionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFbSportsMatchMarketGroupSelectionDo
	Not(conds ...gen.Condition) IFbSportsMatchMarketGroupSelectionDo
	Or(conds ...gen.Condition) IFbSportsMatchMarketGroupSelectionDo
	Select(conds ...field.Expr) IFbSportsMatchMarketGroupSelectionDo
	Where(conds ...gen.Condition) IFbSportsMatchMarketGroupSelectionDo
	Order(conds ...field.Expr) IFbSportsMatchMarketGroupSelectionDo
	Distinct(cols ...field.Expr) IFbSportsMatchMarketGroupSelectionDo
	Omit(cols ...field.Expr) IFbSportsMatchMarketGroupSelectionDo
	Join(table schema.Tabler, on ...field.Expr) IFbSportsMatchMarketGroupSelectionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFbSportsMatchMarketGroupSelectionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFbSportsMatchMarketGroupSelectionDo
	Group(cols ...field.Expr) IFbSportsMatchMarketGroupSelectionDo
	Having(conds ...gen.Condition) IFbSportsMatchMarketGroupSelectionDo
	Limit(limit int) IFbSportsMatchMarketGroupSelectionDo
	Offset(offset int) IFbSportsMatchMarketGroupSelectionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFbSportsMatchMarketGroupSelectionDo
	Unscoped() IFbSportsMatchMarketGroupSelectionDo
	Create(values ...*model.FbSportsMatchMarketGroupSelection) error
	CreateInBatches(values []*model.FbSportsMatchMarketGroupSelection, batchSize int) error
	Save(values ...*model.FbSportsMatchMarketGroupSelection) error
	First() (*model.FbSportsMatchMarketGroupSelection, error)
	Take() (*model.FbSportsMatchMarketGroupSelection, error)
	Last() (*model.FbSportsMatchMarketGroupSelection, error)
	Find() ([]*model.FbSportsMatchMarketGroupSelection, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FbSportsMatchMarketGroupSelection, err error)
	FindInBatches(result *[]*model.FbSportsMatchMarketGroupSelection, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FbSportsMatchMarketGroupSelection) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFbSportsMatchMarketGroupSelectionDo
	Assign(attrs ...field.AssignExpr) IFbSportsMatchMarketGroupSelectionDo
	Joins(fields ...field.RelationField) IFbSportsMatchMarketGroupSelectionDo
	Preload(fields ...field.RelationField) IFbSportsMatchMarketGroupSelectionDo
	FirstOrInit() (*model.FbSportsMatchMarketGroupSelection, error)
	FirstOrCreate() (*model.FbSportsMatchMarketGroupSelection, error)
	FindByPage(offset int, limit int) (result []*model.FbSportsMatchMarketGroupSelection, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFbSportsMatchMarketGroupSelectionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f fbSportsMatchMarketGroupSelectionDo) Debug() IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Debug())
}

func (f fbSportsMatchMarketGroupSelectionDo) WithContext(ctx context.Context) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fbSportsMatchMarketGroupSelectionDo) ReadDB() IFbSportsMatchMarketGroupSelectionDo {
	return f.Clauses(dbresolver.Read)
}

func (f fbSportsMatchMarketGroupSelectionDo) WriteDB() IFbSportsMatchMarketGroupSelectionDo {
	return f.Clauses(dbresolver.Write)
}

func (f fbSportsMatchMarketGroupSelectionDo) Session(config *gorm.Session) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Session(config))
}

func (f fbSportsMatchMarketGroupSelectionDo) Clauses(conds ...clause.Expression) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Returning(value interface{}, columns ...string) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Not(conds ...gen.Condition) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Or(conds ...gen.Condition) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Select(conds ...field.Expr) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Where(conds ...gen.Condition) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Order(conds ...field.Expr) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Distinct(cols ...field.Expr) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Omit(cols ...field.Expr) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Join(table schema.Tabler, on ...field.Expr) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fbSportsMatchMarketGroupSelectionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fbSportsMatchMarketGroupSelectionDo) RightJoin(table schema.Tabler, on ...field.Expr) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Group(cols ...field.Expr) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Having(conds ...gen.Condition) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Limit(limit int) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fbSportsMatchMarketGroupSelectionDo) Offset(offset int) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fbSportsMatchMarketGroupSelectionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Unscoped() IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fbSportsMatchMarketGroupSelectionDo) Create(values ...*model.FbSportsMatchMarketGroupSelection) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fbSportsMatchMarketGroupSelectionDo) CreateInBatches(values []*model.FbSportsMatchMarketGroupSelection, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fbSportsMatchMarketGroupSelectionDo) Save(values ...*model.FbSportsMatchMarketGroupSelection) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fbSportsMatchMarketGroupSelectionDo) First() (*model.FbSportsMatchMarketGroupSelection, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbSportsMatchMarketGroupSelection), nil
	}
}

func (f fbSportsMatchMarketGroupSelectionDo) Take() (*model.FbSportsMatchMarketGroupSelection, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbSportsMatchMarketGroupSelection), nil
	}
}

func (f fbSportsMatchMarketGroupSelectionDo) Last() (*model.FbSportsMatchMarketGroupSelection, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbSportsMatchMarketGroupSelection), nil
	}
}

func (f fbSportsMatchMarketGroupSelectionDo) Find() ([]*model.FbSportsMatchMarketGroupSelection, error) {
	result, err := f.DO.Find()
	return result.([]*model.FbSportsMatchMarketGroupSelection), err
}

func (f fbSportsMatchMarketGroupSelectionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FbSportsMatchMarketGroupSelection, err error) {
	buf := make([]*model.FbSportsMatchMarketGroupSelection, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fbSportsMatchMarketGroupSelectionDo) FindInBatches(result *[]*model.FbSportsMatchMarketGroupSelection, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fbSportsMatchMarketGroupSelectionDo) Attrs(attrs ...field.AssignExpr) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Assign(attrs ...field.AssignExpr) IFbSportsMatchMarketGroupSelectionDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fbSportsMatchMarketGroupSelectionDo) Joins(fields ...field.RelationField) IFbSportsMatchMarketGroupSelectionDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fbSportsMatchMarketGroupSelectionDo) Preload(fields ...field.RelationField) IFbSportsMatchMarketGroupSelectionDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fbSportsMatchMarketGroupSelectionDo) FirstOrInit() (*model.FbSportsMatchMarketGroupSelection, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbSportsMatchMarketGroupSelection), nil
	}
}

func (f fbSportsMatchMarketGroupSelectionDo) FirstOrCreate() (*model.FbSportsMatchMarketGroupSelection, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbSportsMatchMarketGroupSelection), nil
	}
}

func (f fbSportsMatchMarketGroupSelectionDo) FindByPage(offset int, limit int) (result []*model.FbSportsMatchMarketGroupSelection, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fbSportsMatchMarketGroupSelectionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fbSportsMatchMarketGroupSelectionDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fbSportsMatchMarketGroupSelectionDo) Delete(models ...*model.FbSportsMatchMarketGroupSelection) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fbSportsMatchMarketGroupSelectionDo) withDO(do gen.Dao) *fbSportsMatchMarketGroupSelectionDo {
	f.DO = *do.(*gen.DO)
	return f
}
