// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gzorm/commons/zorm/model"
)

func newTRankingFakeRecord(db *gorm.DB, opts ...gen.DOOption) tRankingFakeRecord {
	_tRankingFakeRecord := tRankingFakeRecord{}

	_tRankingFakeRecord.tRankingFakeRecordDo.UseDB(db, opts...)
	_tRankingFakeRecord.tRankingFakeRecordDo.UseModel(&model.TRankingFakeRecord{})

	tableName := _tRankingFakeRecord.tRankingFakeRecordDo.TableName()
	_tRankingFakeRecord.ALL = field.NewAsterisk(tableName)
	_tRankingFakeRecord.ID = field.NewInt64(tableName, "id")
	_tRankingFakeRecord.RankingType = field.NewString(tableName, "ranking_type")
	_tRankingFakeRecord.Period = field.NewString(tableName, "period")
	_tRankingFakeRecord.Currency = field.NewString(tableName, "currency")
	_tRankingFakeRecord.FakeUID = field.NewInt64(tableName, "fake_uid")
	_tRankingFakeRecord.Username = field.NewString(tableName, "username")
	_tRankingFakeRecord.Avatar = field.NewString(tableName, "avatar")
	_tRankingFakeRecord.FirstLetter = field.NewString(tableName, "first_letter")
	_tRankingFakeRecord.VipLevel = field.NewInt64(tableName, "vip_level")
	_tRankingFakeRecord.Tags = field.NewString(tableName, "tags")
	_tRankingFakeRecord.TotalBet = field.NewField(tableName, "total_bet")
	_tRankingFakeRecord.ValidBet = field.NewField(tableName, "valid_bet")
	_tRankingFakeRecord.Profit = field.NewField(tableName, "profit")
	_tRankingFakeRecord.RechargeAmount = field.NewField(tableName, "recharge_amount")
	_tRankingFakeRecord.Rank = field.NewInt64(tableName, "rank")
	_tRankingFakeRecord.Status = field.NewInt64(tableName, "status")
	_tRankingFakeRecord.CreatedAt = field.NewInt64(tableName, "created_at")
	_tRankingFakeRecord.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_tRankingFakeRecord.fillFieldMap()

	return _tRankingFakeRecord
}

// tRankingFakeRecord 盈利排行榜
type tRankingFakeRecord struct {
	tRankingFakeRecordDo

	ALL            field.Asterisk
	ID             field.Int64
	RankingType    field.String // ranking type: profit/recharge
	Period         field.String // ranking period: live/daily/historical
	Currency       field.String // currency: EGP/USDT, empty for profit ranking
	FakeUID        field.Int64  // fake user id
	Username       field.String // display username
	Avatar         field.String // avatar url
	FirstLetter    field.String // first letter
	VipLevel       field.Int64  // vip level
	Tags           field.String // comma separated tags
	TotalBet       field.Field  // fake total bet
	ValidBet       field.Field  // fake valid bet
	Profit         field.Field  // fake profit amount
	RechargeAmount field.Field  // fake recharge amount
	Rank           field.Int64  // fake ranking order
	Status         field.Int64  // status: 1 enabled 0 disabled
	CreatedAt      field.Int64
	UpdatedAt      field.Int64

	fieldMap map[string]field.Expr
}

func (t tRankingFakeRecord) Table(newTableName string) *tRankingFakeRecord {
	t.tRankingFakeRecordDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tRankingFakeRecord) As(alias string) *tRankingFakeRecord {
	t.tRankingFakeRecordDo.DO = *(t.tRankingFakeRecordDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tRankingFakeRecord) updateTableName(table string) *tRankingFakeRecord {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.RankingType = field.NewString(table, "ranking_type")
	t.Period = field.NewString(table, "period")
	t.Currency = field.NewString(table, "currency")
	t.FakeUID = field.NewInt64(table, "fake_uid")
	t.Username = field.NewString(table, "username")
	t.Avatar = field.NewString(table, "avatar")
	t.FirstLetter = field.NewString(table, "first_letter")
	t.VipLevel = field.NewInt64(table, "vip_level")
	t.Tags = field.NewString(table, "tags")
	t.TotalBet = field.NewField(table, "total_bet")
	t.ValidBet = field.NewField(table, "valid_bet")
	t.Profit = field.NewField(table, "profit")
	t.RechargeAmount = field.NewField(table, "recharge_amount")
	t.Rank = field.NewInt64(table, "rank")
	t.Status = field.NewInt64(table, "status")
	t.CreatedAt = field.NewInt64(table, "created_at")
	t.UpdatedAt = field.NewInt64(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tRankingFakeRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tRankingFakeRecord) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 18)
	t.fieldMap["id"] = t.ID
	t.fieldMap["ranking_type"] = t.RankingType
	t.fieldMap["period"] = t.Period
	t.fieldMap["currency"] = t.Currency
	t.fieldMap["fake_uid"] = t.FakeUID
	t.fieldMap["username"] = t.Username
	t.fieldMap["avatar"] = t.Avatar
	t.fieldMap["first_letter"] = t.FirstLetter
	t.fieldMap["vip_level"] = t.VipLevel
	t.fieldMap["tags"] = t.Tags
	t.fieldMap["total_bet"] = t.TotalBet
	t.fieldMap["valid_bet"] = t.ValidBet
	t.fieldMap["profit"] = t.Profit
	t.fieldMap["recharge_amount"] = t.RechargeAmount
	t.fieldMap["rank"] = t.Rank
	t.fieldMap["status"] = t.Status
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tRankingFakeRecord) clone(db *gorm.DB) tRankingFakeRecord {
	t.tRankingFakeRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tRankingFakeRecord) replaceDB(db *gorm.DB) tRankingFakeRecord {
	t.tRankingFakeRecordDo.ReplaceDB(db)
	return t
}

type tRankingFakeRecordDo struct{ gen.DO }

type ITRankingFakeRecordDo interface {
	gen.SubQuery
	Debug() ITRankingFakeRecordDo
	WithContext(ctx context.Context) ITRankingFakeRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITRankingFakeRecordDo
	WriteDB() ITRankingFakeRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITRankingFakeRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITRankingFakeRecordDo
	Not(conds ...gen.Condition) ITRankingFakeRecordDo
	Or(conds ...gen.Condition) ITRankingFakeRecordDo
	Select(conds ...field.Expr) ITRankingFakeRecordDo
	Where(conds ...gen.Condition) ITRankingFakeRecordDo
	Order(conds ...field.Expr) ITRankingFakeRecordDo
	Distinct(cols ...field.Expr) ITRankingFakeRecordDo
	Omit(cols ...field.Expr) ITRankingFakeRecordDo
	Join(table schema.Tabler, on ...field.Expr) ITRankingFakeRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITRankingFakeRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITRankingFakeRecordDo
	Group(cols ...field.Expr) ITRankingFakeRecordDo
	Having(conds ...gen.Condition) ITRankingFakeRecordDo
	Limit(limit int) ITRankingFakeRecordDo
	Offset(offset int) ITRankingFakeRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITRankingFakeRecordDo
	Unscoped() ITRankingFakeRecordDo
	Create(values ...*model.TRankingFakeRecord) error
	CreateInBatches(values []*model.TRankingFakeRecord, batchSize int) error
	Save(values ...*model.TRankingFakeRecord) error
	First() (*model.TRankingFakeRecord, error)
	Take() (*model.TRankingFakeRecord, error)
	Last() (*model.TRankingFakeRecord, error)
	Find() ([]*model.TRankingFakeRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TRankingFakeRecord, err error)
	FindInBatches(result *[]*model.TRankingFakeRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TRankingFakeRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITRankingFakeRecordDo
	Assign(attrs ...field.AssignExpr) ITRankingFakeRecordDo
	Joins(fields ...field.RelationField) ITRankingFakeRecordDo
	Preload(fields ...field.RelationField) ITRankingFakeRecordDo
	FirstOrInit() (*model.TRankingFakeRecord, error)
	FirstOrCreate() (*model.TRankingFakeRecord, error)
	FindByPage(offset int, limit int) (result []*model.TRankingFakeRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITRankingFakeRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tRankingFakeRecordDo) Debug() ITRankingFakeRecordDo {
	return t.withDO(t.DO.Debug())
}

func (t tRankingFakeRecordDo) WithContext(ctx context.Context) ITRankingFakeRecordDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tRankingFakeRecordDo) ReadDB() ITRankingFakeRecordDo {
	return t.Clauses(dbresolver.Read)
}

func (t tRankingFakeRecordDo) WriteDB() ITRankingFakeRecordDo {
	return t.Clauses(dbresolver.Write)
}

func (t tRankingFakeRecordDo) Session(config *gorm.Session) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Session(config))
}

func (t tRankingFakeRecordDo) Clauses(conds ...clause.Expression) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tRankingFakeRecordDo) Returning(value interface{}, columns ...string) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tRankingFakeRecordDo) Not(conds ...gen.Condition) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tRankingFakeRecordDo) Or(conds ...gen.Condition) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tRankingFakeRecordDo) Select(conds ...field.Expr) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tRankingFakeRecordDo) Where(conds ...gen.Condition) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tRankingFakeRecordDo) Order(conds ...field.Expr) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tRankingFakeRecordDo) Distinct(cols ...field.Expr) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tRankingFakeRecordDo) Omit(cols ...field.Expr) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tRankingFakeRecordDo) Join(table schema.Tabler, on ...field.Expr) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tRankingFakeRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITRankingFakeRecordDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tRankingFakeRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) ITRankingFakeRecordDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tRankingFakeRecordDo) Group(cols ...field.Expr) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tRankingFakeRecordDo) Having(conds ...gen.Condition) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tRankingFakeRecordDo) Limit(limit int) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tRankingFakeRecordDo) Offset(offset int) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tRankingFakeRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tRankingFakeRecordDo) Unscoped() ITRankingFakeRecordDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tRankingFakeRecordDo) Create(values ...*model.TRankingFakeRecord) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tRankingFakeRecordDo) CreateInBatches(values []*model.TRankingFakeRecord, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tRankingFakeRecordDo) Save(values ...*model.TRankingFakeRecord) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tRankingFakeRecordDo) First() (*model.TRankingFakeRecord, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TRankingFakeRecord), nil
	}
}

func (t tRankingFakeRecordDo) Take() (*model.TRankingFakeRecord, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TRankingFakeRecord), nil
	}
}

func (t tRankingFakeRecordDo) Last() (*model.TRankingFakeRecord, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TRankingFakeRecord), nil
	}
}

func (t tRankingFakeRecordDo) Find() ([]*model.TRankingFakeRecord, error) {
	result, err := t.DO.Find()
	return result.([]*model.TRankingFakeRecord), err
}

func (t tRankingFakeRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TRankingFakeRecord, err error) {
	buf := make([]*model.TRankingFakeRecord, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tRankingFakeRecordDo) FindInBatches(result *[]*model.TRankingFakeRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tRankingFakeRecordDo) Attrs(attrs ...field.AssignExpr) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tRankingFakeRecordDo) Assign(attrs ...field.AssignExpr) ITRankingFakeRecordDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tRankingFakeRecordDo) Joins(fields ...field.RelationField) ITRankingFakeRecordDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tRankingFakeRecordDo) Preload(fields ...field.RelationField) ITRankingFakeRecordDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tRankingFakeRecordDo) FirstOrInit() (*model.TRankingFakeRecord, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TRankingFakeRecord), nil
	}
}

func (t tRankingFakeRecordDo) FirstOrCreate() (*model.TRankingFakeRecord, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TRankingFakeRecord), nil
	}
}

func (t tRankingFakeRecordDo) FindByPage(offset int, limit int) (result []*model.TRankingFakeRecord, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tRankingFakeRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tRankingFakeRecordDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tRankingFakeRecordDo) Delete(models ...*model.TRankingFakeRecord) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tRankingFakeRecordDo) withDO(do gen.Dao) *tRankingFakeRecordDo {
	t.DO = *do.(*gen.DO)
	return t
}
