// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gzorm/commons/zorm/model"
)

func newWinRankingUser(db *gorm.DB, opts ...gen.DOOption) winRankingUser {
	_winRankingUser := winRankingUser{}

	_winRankingUser.winRankingUserDo.UseDB(db, opts...)
	_winRankingUser.winRankingUserDo.UseModel(&model.WinRankingUser{})

	tableName := _winRankingUser.winRankingUserDo.TableName()
	_winRankingUser.ALL = field.NewAsterisk(tableName)
	_winRankingUser.ID = field.NewInt64(tableName, "id")
	_winRankingUser.UID = field.NewInt64(tableName, "uid")
	_winRankingUser.Username = field.NewString(tableName, "username")
	_winRankingUser.Avatar = field.NewString(tableName, "avatar")
	_winRankingUser.FirstLetter = field.NewString(tableName, "first_letter")
	_winRankingUser.VipLevel = field.NewInt64(tableName, "vip_level")
	_winRankingUser.IsRobot = field.NewInt64(tableName, "is_robot")
	_winRankingUser.Tags = field.NewString(tableName, "tags")
	_winRankingUser.TotalBet = field.NewField(tableName, "total_bet")
	_winRankingUser.ValidBet = field.NewField(tableName, "valid_bet")
	_winRankingUser.Profit = field.NewField(tableName, "profit")
	_winRankingUser.Rank = field.NewInt64(tableName, "rank")
	_winRankingUser.RankType = field.NewString(tableName, "rank_type")
	_winRankingUser.UpdatedTime = field.NewString(tableName, "updated_time")
	_winRankingUser.CreatedAt = field.NewInt64(tableName, "created_at")
	_winRankingUser.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_winRankingUser.fillFieldMap()

	return _winRankingUser
}

// winRankingUser 排行榜用户数据表
type winRankingUser struct {
	winRankingUserDo

	ALL         field.Asterisk
	ID          field.Int64
	UID         field.Int64  // 用户ID
	Username    field.String // 用户名(脱敏)
	Avatar      field.String // 头像URL
	FirstLetter field.String // 名字首字母
	VipLevel    field.Int64  // VIP等级
	IsRobot     field.Int64  // 是否机器人 1=是 0=否
	Tags        field.String // 标签,逗号分隔
	TotalBet    field.Field  // 总投注额
	ValidBet    field.Field  // 有效投注额
	Profit      field.Field  // 利润/奖金
	Rank        field.Int64  // 当前排名
	RankType    field.String // 排行榜类型: historical/daily/live
	UpdatedTime field.String // 更新时间 MM-dd HH:mm
	CreatedAt   field.Int64  // 创建时间戳
	UpdatedAt   field.Int64  // 更新时间戳

	fieldMap map[string]field.Expr
}

func (w winRankingUser) Table(newTableName string) *winRankingUser {
	w.winRankingUserDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w winRankingUser) As(alias string) *winRankingUser {
	w.winRankingUserDo.DO = *(w.winRankingUserDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *winRankingUser) updateTableName(table string) *winRankingUser {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.UID = field.NewInt64(table, "uid")
	w.Username = field.NewString(table, "username")
	w.Avatar = field.NewString(table, "avatar")
	w.FirstLetter = field.NewString(table, "first_letter")
	w.VipLevel = field.NewInt64(table, "vip_level")
	w.IsRobot = field.NewInt64(table, "is_robot")
	w.Tags = field.NewString(table, "tags")
	w.TotalBet = field.NewField(table, "total_bet")
	w.ValidBet = field.NewField(table, "valid_bet")
	w.Profit = field.NewField(table, "profit")
	w.Rank = field.NewInt64(table, "rank")
	w.RankType = field.NewString(table, "rank_type")
	w.UpdatedTime = field.NewString(table, "updated_time")
	w.CreatedAt = field.NewInt64(table, "created_at")
	w.UpdatedAt = field.NewInt64(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *winRankingUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *winRankingUser) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 16)
	w.fieldMap["id"] = w.ID
	w.fieldMap["uid"] = w.UID
	w.fieldMap["username"] = w.Username
	w.fieldMap["avatar"] = w.Avatar
	w.fieldMap["first_letter"] = w.FirstLetter
	w.fieldMap["vip_level"] = w.VipLevel
	w.fieldMap["is_robot"] = w.IsRobot
	w.fieldMap["tags"] = w.Tags
	w.fieldMap["total_bet"] = w.TotalBet
	w.fieldMap["valid_bet"] = w.ValidBet
	w.fieldMap["profit"] = w.Profit
	w.fieldMap["rank"] = w.Rank
	w.fieldMap["rank_type"] = w.RankType
	w.fieldMap["updated_time"] = w.UpdatedTime
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w winRankingUser) clone(db *gorm.DB) winRankingUser {
	w.winRankingUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w winRankingUser) replaceDB(db *gorm.DB) winRankingUser {
	w.winRankingUserDo.ReplaceDB(db)
	return w
}

type winRankingUserDo struct{ gen.DO }

type IWinRankingUserDo interface {
	gen.SubQuery
	Debug() IWinRankingUserDo
	WithContext(ctx context.Context) IWinRankingUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWinRankingUserDo
	WriteDB() IWinRankingUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWinRankingUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWinRankingUserDo
	Not(conds ...gen.Condition) IWinRankingUserDo
	Or(conds ...gen.Condition) IWinRankingUserDo
	Select(conds ...field.Expr) IWinRankingUserDo
	Where(conds ...gen.Condition) IWinRankingUserDo
	Order(conds ...field.Expr) IWinRankingUserDo
	Distinct(cols ...field.Expr) IWinRankingUserDo
	Omit(cols ...field.Expr) IWinRankingUserDo
	Join(table schema.Tabler, on ...field.Expr) IWinRankingUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWinRankingUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWinRankingUserDo
	Group(cols ...field.Expr) IWinRankingUserDo
	Having(conds ...gen.Condition) IWinRankingUserDo
	Limit(limit int) IWinRankingUserDo
	Offset(offset int) IWinRankingUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWinRankingUserDo
	Unscoped() IWinRankingUserDo
	Create(values ...*model.WinRankingUser) error
	CreateInBatches(values []*model.WinRankingUser, batchSize int) error
	Save(values ...*model.WinRankingUser) error
	First() (*model.WinRankingUser, error)
	Take() (*model.WinRankingUser, error)
	Last() (*model.WinRankingUser, error)
	Find() ([]*model.WinRankingUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WinRankingUser, err error)
	FindInBatches(result *[]*model.WinRankingUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WinRankingUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWinRankingUserDo
	Assign(attrs ...field.AssignExpr) IWinRankingUserDo
	Joins(fields ...field.RelationField) IWinRankingUserDo
	Preload(fields ...field.RelationField) IWinRankingUserDo
	FirstOrInit() (*model.WinRankingUser, error)
	FirstOrCreate() (*model.WinRankingUser, error)
	FindByPage(offset int, limit int) (result []*model.WinRankingUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWinRankingUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w winRankingUserDo) Debug() IWinRankingUserDo {
	return w.withDO(w.DO.Debug())
}

func (w winRankingUserDo) WithContext(ctx context.Context) IWinRankingUserDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w winRankingUserDo) ReadDB() IWinRankingUserDo {
	return w.Clauses(dbresolver.Read)
}

func (w winRankingUserDo) WriteDB() IWinRankingUserDo {
	return w.Clauses(dbresolver.Write)
}

func (w winRankingUserDo) Session(config *gorm.Session) IWinRankingUserDo {
	return w.withDO(w.DO.Session(config))
}

func (w winRankingUserDo) Clauses(conds ...clause.Expression) IWinRankingUserDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w winRankingUserDo) Returning(value interface{}, columns ...string) IWinRankingUserDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w winRankingUserDo) Not(conds ...gen.Condition) IWinRankingUserDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w winRankingUserDo) Or(conds ...gen.Condition) IWinRankingUserDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w winRankingUserDo) Select(conds ...field.Expr) IWinRankingUserDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w winRankingUserDo) Where(conds ...gen.Condition) IWinRankingUserDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w winRankingUserDo) Order(conds ...field.Expr) IWinRankingUserDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w winRankingUserDo) Distinct(cols ...field.Expr) IWinRankingUserDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w winRankingUserDo) Omit(cols ...field.Expr) IWinRankingUserDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w winRankingUserDo) Join(table schema.Tabler, on ...field.Expr) IWinRankingUserDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w winRankingUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWinRankingUserDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w winRankingUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IWinRankingUserDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w winRankingUserDo) Group(cols ...field.Expr) IWinRankingUserDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w winRankingUserDo) Having(conds ...gen.Condition) IWinRankingUserDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w winRankingUserDo) Limit(limit int) IWinRankingUserDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w winRankingUserDo) Offset(offset int) IWinRankingUserDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w winRankingUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWinRankingUserDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w winRankingUserDo) Unscoped() IWinRankingUserDo {
	return w.withDO(w.DO.Unscoped())
}

func (w winRankingUserDo) Create(values ...*model.WinRankingUser) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w winRankingUserDo) CreateInBatches(values []*model.WinRankingUser, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w winRankingUserDo) Save(values ...*model.WinRankingUser) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w winRankingUserDo) First() (*model.WinRankingUser, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinRankingUser), nil
	}
}

func (w winRankingUserDo) Take() (*model.WinRankingUser, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinRankingUser), nil
	}
}

func (w winRankingUserDo) Last() (*model.WinRankingUser, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinRankingUser), nil
	}
}

func (w winRankingUserDo) Find() ([]*model.WinRankingUser, error) {
	result, err := w.DO.Find()
	return result.([]*model.WinRankingUser), err
}

func (w winRankingUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WinRankingUser, err error) {
	buf := make([]*model.WinRankingUser, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w winRankingUserDo) FindInBatches(result *[]*model.WinRankingUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w winRankingUserDo) Attrs(attrs ...field.AssignExpr) IWinRankingUserDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w winRankingUserDo) Assign(attrs ...field.AssignExpr) IWinRankingUserDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w winRankingUserDo) Joins(fields ...field.RelationField) IWinRankingUserDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w winRankingUserDo) Preload(fields ...field.RelationField) IWinRankingUserDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w winRankingUserDo) FirstOrInit() (*model.WinRankingUser, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinRankingUser), nil
	}
}

func (w winRankingUserDo) FirstOrCreate() (*model.WinRankingUser, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinRankingUser), nil
	}
}

func (w winRankingUserDo) FindByPage(offset int, limit int) (result []*model.WinRankingUser, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w winRankingUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w winRankingUserDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w winRankingUserDo) Delete(models ...*model.WinRankingUser) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *winRankingUserDo) withDO(do gen.Dao) *winRankingUserDo {
	w.DO = *do.(*gen.DO)
	return w
}
