// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gzorm/commons/zorm/model"
)

func newWinLuckyUserTotalStat(db *gorm.DB, opts ...gen.DOOption) winLuckyUserTotalStat {
	_winLuckyUserTotalStat := winLuckyUserTotalStat{}

	_winLuckyUserTotalStat.winLuckyUserTotalStatDo.UseDB(db, opts...)
	_winLuckyUserTotalStat.winLuckyUserTotalStatDo.UseModel(&model.WinLuckyUserTotalStat{})

	tableName := _winLuckyUserTotalStat.winLuckyUserTotalStatDo.TableName()
	_winLuckyUserTotalStat.ALL = field.NewAsterisk(tableName)
	_winLuckyUserTotalStat.ID = field.NewInt64(tableName, "id")
	_winLuckyUserTotalStat.DrawConfigID = field.NewInt64(tableName, "draw_config_id")
	_winLuckyUserTotalStat.UID = field.NewInt64(tableName, "uid")
	_winLuckyUserTotalStat.Username = field.NewString(tableName, "username")
	_winLuckyUserTotalStat.Currency = field.NewString(tableName, "currency")
	_winLuckyUserTotalStat.RiskFlag = field.NewInt64(tableName, "risk_flag")
	_winLuckyUserTotalStat.TotalBetCount = field.NewInt64(tableName, "total_bet_count")
	_winLuckyUserTotalStat.TotalBetAmount = field.NewField(tableName, "total_bet_amount")
	_winLuckyUserTotalStat.TotalWinCount = field.NewInt64(tableName, "total_win_count")
	_winLuckyUserTotalStat.TotalWinAmount = field.NewField(tableName, "total_win_amount")
	_winLuckyUserTotalStat.TotalClaimCount = field.NewInt64(tableName, "total_claim_count")
	_winLuckyUserTotalStat.TotalClaimAmount = field.NewField(tableName, "total_claim_amount")
	_winLuckyUserTotalStat.LastWinAt = field.NewInt64(tableName, "last_win_at")
	_winLuckyUserTotalStat.LastClaimAt = field.NewInt64(tableName, "last_claim_at")
	_winLuckyUserTotalStat.CreatedAt = field.NewInt64(tableName, "created_at")
	_winLuckyUserTotalStat.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_winLuckyUserTotalStat.fillFieldMap()

	return _winLuckyUserTotalStat
}

// winLuckyUserTotalStat Lucky 用户累计统计表
type winLuckyUserTotalStat struct {
	winLuckyUserTotalStatDo

	ALL              field.Asterisk
	ID               field.Int64  // 主键ID
	DrawConfigID     field.Int64  // 活动主配置ID
	UID              field.Int64  // 用户ID
	Username         field.String // 用户名
	Currency         field.String // 币种
	RiskFlag         field.Int64  // 风控标记 0正常 1可疑
	TotalBetCount    field.Int64  // 累计下注次数
	TotalBetAmount   field.Field  // 累计下注总额
	TotalWinCount    field.Int64  // 累计中奖次数
	TotalWinAmount   field.Field  // 累计中奖总额
	TotalClaimCount  field.Int64  // 累计领取次数
	TotalClaimAmount field.Field  // 累计领取总额
	LastWinAt        field.Int64  // 最后中奖时间
	LastClaimAt      field.Int64  // 最后领取时间
	CreatedAt        field.Int64  // 创建时间
	UpdatedAt        field.Int64  // 更新时间

	fieldMap map[string]field.Expr
}

func (w winLuckyUserTotalStat) Table(newTableName string) *winLuckyUserTotalStat {
	w.winLuckyUserTotalStatDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w winLuckyUserTotalStat) As(alias string) *winLuckyUserTotalStat {
	w.winLuckyUserTotalStatDo.DO = *(w.winLuckyUserTotalStatDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *winLuckyUserTotalStat) updateTableName(table string) *winLuckyUserTotalStat {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.DrawConfigID = field.NewInt64(table, "draw_config_id")
	w.UID = field.NewInt64(table, "uid")
	w.Username = field.NewString(table, "username")
	w.Currency = field.NewString(table, "currency")
	w.RiskFlag = field.NewInt64(table, "risk_flag")
	w.TotalBetCount = field.NewInt64(table, "total_bet_count")
	w.TotalBetAmount = field.NewField(table, "total_bet_amount")
	w.TotalWinCount = field.NewInt64(table, "total_win_count")
	w.TotalWinAmount = field.NewField(table, "total_win_amount")
	w.TotalClaimCount = field.NewInt64(table, "total_claim_count")
	w.TotalClaimAmount = field.NewField(table, "total_claim_amount")
	w.LastWinAt = field.NewInt64(table, "last_win_at")
	w.LastClaimAt = field.NewInt64(table, "last_claim_at")
	w.CreatedAt = field.NewInt64(table, "created_at")
	w.UpdatedAt = field.NewInt64(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *winLuckyUserTotalStat) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *winLuckyUserTotalStat) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 16)
	w.fieldMap["id"] = w.ID
	w.fieldMap["draw_config_id"] = w.DrawConfigID
	w.fieldMap["uid"] = w.UID
	w.fieldMap["username"] = w.Username
	w.fieldMap["currency"] = w.Currency
	w.fieldMap["risk_flag"] = w.RiskFlag
	w.fieldMap["total_bet_count"] = w.TotalBetCount
	w.fieldMap["total_bet_amount"] = w.TotalBetAmount
	w.fieldMap["total_win_count"] = w.TotalWinCount
	w.fieldMap["total_win_amount"] = w.TotalWinAmount
	w.fieldMap["total_claim_count"] = w.TotalClaimCount
	w.fieldMap["total_claim_amount"] = w.TotalClaimAmount
	w.fieldMap["last_win_at"] = w.LastWinAt
	w.fieldMap["last_claim_at"] = w.LastClaimAt
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w winLuckyUserTotalStat) clone(db *gorm.DB) winLuckyUserTotalStat {
	w.winLuckyUserTotalStatDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w winLuckyUserTotalStat) replaceDB(db *gorm.DB) winLuckyUserTotalStat {
	w.winLuckyUserTotalStatDo.ReplaceDB(db)
	return w
}

type winLuckyUserTotalStatDo struct{ gen.DO }

type IWinLuckyUserTotalStatDo interface {
	gen.SubQuery
	Debug() IWinLuckyUserTotalStatDo
	WithContext(ctx context.Context) IWinLuckyUserTotalStatDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWinLuckyUserTotalStatDo
	WriteDB() IWinLuckyUserTotalStatDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWinLuckyUserTotalStatDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWinLuckyUserTotalStatDo
	Not(conds ...gen.Condition) IWinLuckyUserTotalStatDo
	Or(conds ...gen.Condition) IWinLuckyUserTotalStatDo
	Select(conds ...field.Expr) IWinLuckyUserTotalStatDo
	Where(conds ...gen.Condition) IWinLuckyUserTotalStatDo
	Order(conds ...field.Expr) IWinLuckyUserTotalStatDo
	Distinct(cols ...field.Expr) IWinLuckyUserTotalStatDo
	Omit(cols ...field.Expr) IWinLuckyUserTotalStatDo
	Join(table schema.Tabler, on ...field.Expr) IWinLuckyUserTotalStatDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWinLuckyUserTotalStatDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWinLuckyUserTotalStatDo
	Group(cols ...field.Expr) IWinLuckyUserTotalStatDo
	Having(conds ...gen.Condition) IWinLuckyUserTotalStatDo
	Limit(limit int) IWinLuckyUserTotalStatDo
	Offset(offset int) IWinLuckyUserTotalStatDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWinLuckyUserTotalStatDo
	Unscoped() IWinLuckyUserTotalStatDo
	Create(values ...*model.WinLuckyUserTotalStat) error
	CreateInBatches(values []*model.WinLuckyUserTotalStat, batchSize int) error
	Save(values ...*model.WinLuckyUserTotalStat) error
	First() (*model.WinLuckyUserTotalStat, error)
	Take() (*model.WinLuckyUserTotalStat, error)
	Last() (*model.WinLuckyUserTotalStat, error)
	Find() ([]*model.WinLuckyUserTotalStat, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WinLuckyUserTotalStat, err error)
	FindInBatches(result *[]*model.WinLuckyUserTotalStat, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WinLuckyUserTotalStat) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWinLuckyUserTotalStatDo
	Assign(attrs ...field.AssignExpr) IWinLuckyUserTotalStatDo
	Joins(fields ...field.RelationField) IWinLuckyUserTotalStatDo
	Preload(fields ...field.RelationField) IWinLuckyUserTotalStatDo
	FirstOrInit() (*model.WinLuckyUserTotalStat, error)
	FirstOrCreate() (*model.WinLuckyUserTotalStat, error)
	FindByPage(offset int, limit int) (result []*model.WinLuckyUserTotalStat, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWinLuckyUserTotalStatDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w winLuckyUserTotalStatDo) Debug() IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Debug())
}

func (w winLuckyUserTotalStatDo) WithContext(ctx context.Context) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w winLuckyUserTotalStatDo) ReadDB() IWinLuckyUserTotalStatDo {
	return w.Clauses(dbresolver.Read)
}

func (w winLuckyUserTotalStatDo) WriteDB() IWinLuckyUserTotalStatDo {
	return w.Clauses(dbresolver.Write)
}

func (w winLuckyUserTotalStatDo) Session(config *gorm.Session) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Session(config))
}

func (w winLuckyUserTotalStatDo) Clauses(conds ...clause.Expression) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w winLuckyUserTotalStatDo) Returning(value interface{}, columns ...string) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w winLuckyUserTotalStatDo) Not(conds ...gen.Condition) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w winLuckyUserTotalStatDo) Or(conds ...gen.Condition) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w winLuckyUserTotalStatDo) Select(conds ...field.Expr) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w winLuckyUserTotalStatDo) Where(conds ...gen.Condition) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w winLuckyUserTotalStatDo) Order(conds ...field.Expr) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w winLuckyUserTotalStatDo) Distinct(cols ...field.Expr) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w winLuckyUserTotalStatDo) Omit(cols ...field.Expr) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w winLuckyUserTotalStatDo) Join(table schema.Tabler, on ...field.Expr) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w winLuckyUserTotalStatDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w winLuckyUserTotalStatDo) RightJoin(table schema.Tabler, on ...field.Expr) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w winLuckyUserTotalStatDo) Group(cols ...field.Expr) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w winLuckyUserTotalStatDo) Having(conds ...gen.Condition) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w winLuckyUserTotalStatDo) Limit(limit int) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w winLuckyUserTotalStatDo) Offset(offset int) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w winLuckyUserTotalStatDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w winLuckyUserTotalStatDo) Unscoped() IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Unscoped())
}

func (w winLuckyUserTotalStatDo) Create(values ...*model.WinLuckyUserTotalStat) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w winLuckyUserTotalStatDo) CreateInBatches(values []*model.WinLuckyUserTotalStat, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w winLuckyUserTotalStatDo) Save(values ...*model.WinLuckyUserTotalStat) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w winLuckyUserTotalStatDo) First() (*model.WinLuckyUserTotalStat, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinLuckyUserTotalStat), nil
	}
}

func (w winLuckyUserTotalStatDo) Take() (*model.WinLuckyUserTotalStat, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinLuckyUserTotalStat), nil
	}
}

func (w winLuckyUserTotalStatDo) Last() (*model.WinLuckyUserTotalStat, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinLuckyUserTotalStat), nil
	}
}

func (w winLuckyUserTotalStatDo) Find() ([]*model.WinLuckyUserTotalStat, error) {
	result, err := w.DO.Find()
	return result.([]*model.WinLuckyUserTotalStat), err
}

func (w winLuckyUserTotalStatDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WinLuckyUserTotalStat, err error) {
	buf := make([]*model.WinLuckyUserTotalStat, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w winLuckyUserTotalStatDo) FindInBatches(result *[]*model.WinLuckyUserTotalStat, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w winLuckyUserTotalStatDo) Attrs(attrs ...field.AssignExpr) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w winLuckyUserTotalStatDo) Assign(attrs ...field.AssignExpr) IWinLuckyUserTotalStatDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w winLuckyUserTotalStatDo) Joins(fields ...field.RelationField) IWinLuckyUserTotalStatDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w winLuckyUserTotalStatDo) Preload(fields ...field.RelationField) IWinLuckyUserTotalStatDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w winLuckyUserTotalStatDo) FirstOrInit() (*model.WinLuckyUserTotalStat, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinLuckyUserTotalStat), nil
	}
}

func (w winLuckyUserTotalStatDo) FirstOrCreate() (*model.WinLuckyUserTotalStat, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinLuckyUserTotalStat), nil
	}
}

func (w winLuckyUserTotalStatDo) FindByPage(offset int, limit int) (result []*model.WinLuckyUserTotalStat, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w winLuckyUserTotalStatDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w winLuckyUserTotalStatDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w winLuckyUserTotalStatDo) Delete(models ...*model.WinLuckyUserTotalStat) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *winLuckyUserTotalStatDo) withDO(do gen.Dao) *winLuckyUserTotalStatDo {
	w.DO = *do.(*gen.DO)
	return w
}
