// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao2

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gzorm/commons/zorm/gen/zorm/model"
)

func newWinCodeRecords(db *gorm.DB, opts ...gen.DOOption) winCodeRecords {
	_winCodeRecords := winCodeRecords{}

	_winCodeRecords.winCodeRecordsDo.UseDB(db, opts...)
	_winCodeRecords.winCodeRecordsDo.UseModel(&model.WinCodeRecords{})

	tableName := _winCodeRecords.winCodeRecordsDo.TableName()
	_winCodeRecords.ALL = field.NewAsterisk(tableName)
	_winCodeRecords.ID = field.NewInt64(tableName, "id")
	_winCodeRecords.UID = field.NewInt64(tableName, "uid")
	_winCodeRecords.Username = field.NewString(tableName, "username")
	_winCodeRecords.Coin = field.NewField(tableName, "coin")
	_winCodeRecords.CodeRequire = field.NewField(tableName, "code_require")
	_winCodeRecords.FlowClaim = field.NewField(tableName, "flow_claim")
	_winCodeRecords.RealCode = field.NewField(tableName, "real_code")
	_winCodeRecords.Category = field.NewInt64(tableName, "category")
	_winCodeRecords.CategoryWallet = field.NewInt64(tableName, "category_wallet")
	_winCodeRecords.ReferID = field.NewInt64(tableName, "refer_id")
	_winCodeRecords.ReferWithdrawalID = field.NewInt64(tableName, "refer_withdrawal_id")
	_winCodeRecords.Remarks = field.NewString(tableName, "remarks")
	_winCodeRecords.Status = field.NewInt64(tableName, "status")
	_winCodeRecords.CreatedAt = field.NewInt64(tableName, "created_at")
	_winCodeRecords.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_winCodeRecords.fillFieldMap()

	return _winCodeRecords
}

// winCodeRecords 打码量记录表
type winCodeRecords struct {
	winCodeRecordsDo

	ALL               field.Asterisk
	ID                field.Int64
	UID               field.Int64  // UID
	Username          field.String // 用户名
	Coin              field.Field  // 金额
	CodeRequire       field.Field  // 需求打码量
	FlowClaim         field.Field  // 需求打码倍数
	RealCode          field.Field  // 实际打码量
	Category          field.Int64  // 类型:1-充值 2-签到活动 3- 系统调账 4注册活动 5充值活动
	CategoryWallet    field.Int64  // 钱包类型:支付/游戏/活动/佣金
	ReferID           field.Int64  // 关联ID
	ReferWithdrawalID field.Int64  // 关联提款ID
	Remarks           field.String // 备注
	Status            field.Int64  // 状态:0-未结算 1-结算
	CreatedAt         field.Int64
	UpdatedAt         field.Int64

	fieldMap map[string]field.Expr
}

func (w winCodeRecords) Table(newTableName string) *winCodeRecords {
	w.winCodeRecordsDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w winCodeRecords) As(alias string) *winCodeRecords {
	w.winCodeRecordsDo.DO = *(w.winCodeRecordsDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *winCodeRecords) updateTableName(table string) *winCodeRecords {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.UID = field.NewInt64(table, "uid")
	w.Username = field.NewString(table, "username")
	w.Coin = field.NewField(table, "coin")
	w.CodeRequire = field.NewField(table, "code_require")
	w.FlowClaim = field.NewField(table, "flow_claim")
	w.RealCode = field.NewField(table, "real_code")
	w.Category = field.NewInt64(table, "category")
	w.CategoryWallet = field.NewInt64(table, "category_wallet")
	w.ReferID = field.NewInt64(table, "refer_id")
	w.ReferWithdrawalID = field.NewInt64(table, "refer_withdrawal_id")
	w.Remarks = field.NewString(table, "remarks")
	w.Status = field.NewInt64(table, "status")
	w.CreatedAt = field.NewInt64(table, "created_at")
	w.UpdatedAt = field.NewInt64(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *winCodeRecords) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *winCodeRecords) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 15)
	w.fieldMap["id"] = w.ID
	w.fieldMap["uid"] = w.UID
	w.fieldMap["username"] = w.Username
	w.fieldMap["coin"] = w.Coin
	w.fieldMap["code_require"] = w.CodeRequire
	w.fieldMap["flow_claim"] = w.FlowClaim
	w.fieldMap["real_code"] = w.RealCode
	w.fieldMap["category"] = w.Category
	w.fieldMap["category_wallet"] = w.CategoryWallet
	w.fieldMap["refer_id"] = w.ReferID
	w.fieldMap["refer_withdrawal_id"] = w.ReferWithdrawalID
	w.fieldMap["remarks"] = w.Remarks
	w.fieldMap["status"] = w.Status
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w winCodeRecords) clone(db *gorm.DB) winCodeRecords {
	w.winCodeRecordsDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w winCodeRecords) replaceDB(db *gorm.DB) winCodeRecords {
	w.winCodeRecordsDo.ReplaceDB(db)
	return w
}

type winCodeRecordsDo struct{ gen.DO }

type IWinCodeRecordsDo interface {
	gen.SubQuery
	Debug() IWinCodeRecordsDo
	WithContext(ctx context.Context) IWinCodeRecordsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWinCodeRecordsDo
	WriteDB() IWinCodeRecordsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWinCodeRecordsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWinCodeRecordsDo
	Not(conds ...gen.Condition) IWinCodeRecordsDo
	Or(conds ...gen.Condition) IWinCodeRecordsDo
	Select(conds ...field.Expr) IWinCodeRecordsDo
	Where(conds ...gen.Condition) IWinCodeRecordsDo
	Order(conds ...field.Expr) IWinCodeRecordsDo
	Distinct(cols ...field.Expr) IWinCodeRecordsDo
	Omit(cols ...field.Expr) IWinCodeRecordsDo
	Join(table schema.Tabler, on ...field.Expr) IWinCodeRecordsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWinCodeRecordsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWinCodeRecordsDo
	Group(cols ...field.Expr) IWinCodeRecordsDo
	Having(conds ...gen.Condition) IWinCodeRecordsDo
	Limit(limit int) IWinCodeRecordsDo
	Offset(offset int) IWinCodeRecordsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWinCodeRecordsDo
	Unscoped() IWinCodeRecordsDo
	Create(values ...*model.WinCodeRecords) error
	CreateInBatches(values []*model.WinCodeRecords, batchSize int) error
	Save(values ...*model.WinCodeRecords) error
	First() (*model.WinCodeRecords, error)
	Take() (*model.WinCodeRecords, error)
	Last() (*model.WinCodeRecords, error)
	Find() ([]*model.WinCodeRecords, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WinCodeRecords, err error)
	FindInBatches(result *[]*model.WinCodeRecords, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WinCodeRecords) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWinCodeRecordsDo
	Assign(attrs ...field.AssignExpr) IWinCodeRecordsDo
	Joins(fields ...field.RelationField) IWinCodeRecordsDo
	Preload(fields ...field.RelationField) IWinCodeRecordsDo
	FirstOrInit() (*model.WinCodeRecords, error)
	FirstOrCreate() (*model.WinCodeRecords, error)
	FindByPage(offset int, limit int) (result []*model.WinCodeRecords, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWinCodeRecordsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w winCodeRecordsDo) Debug() IWinCodeRecordsDo {
	return w.withDO(w.DO.Debug())
}

func (w winCodeRecordsDo) WithContext(ctx context.Context) IWinCodeRecordsDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w winCodeRecordsDo) ReadDB() IWinCodeRecordsDo {
	return w.Clauses(dbresolver.Read)
}

func (w winCodeRecordsDo) WriteDB() IWinCodeRecordsDo {
	return w.Clauses(dbresolver.Write)
}

func (w winCodeRecordsDo) Session(config *gorm.Session) IWinCodeRecordsDo {
	return w.withDO(w.DO.Session(config))
}

func (w winCodeRecordsDo) Clauses(conds ...clause.Expression) IWinCodeRecordsDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w winCodeRecordsDo) Returning(value interface{}, columns ...string) IWinCodeRecordsDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w winCodeRecordsDo) Not(conds ...gen.Condition) IWinCodeRecordsDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w winCodeRecordsDo) Or(conds ...gen.Condition) IWinCodeRecordsDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w winCodeRecordsDo) Select(conds ...field.Expr) IWinCodeRecordsDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w winCodeRecordsDo) Where(conds ...gen.Condition) IWinCodeRecordsDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w winCodeRecordsDo) Order(conds ...field.Expr) IWinCodeRecordsDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w winCodeRecordsDo) Distinct(cols ...field.Expr) IWinCodeRecordsDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w winCodeRecordsDo) Omit(cols ...field.Expr) IWinCodeRecordsDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w winCodeRecordsDo) Join(table schema.Tabler, on ...field.Expr) IWinCodeRecordsDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w winCodeRecordsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWinCodeRecordsDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w winCodeRecordsDo) RightJoin(table schema.Tabler, on ...field.Expr) IWinCodeRecordsDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w winCodeRecordsDo) Group(cols ...field.Expr) IWinCodeRecordsDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w winCodeRecordsDo) Having(conds ...gen.Condition) IWinCodeRecordsDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w winCodeRecordsDo) Limit(limit int) IWinCodeRecordsDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w winCodeRecordsDo) Offset(offset int) IWinCodeRecordsDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w winCodeRecordsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWinCodeRecordsDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w winCodeRecordsDo) Unscoped() IWinCodeRecordsDo {
	return w.withDO(w.DO.Unscoped())
}

func (w winCodeRecordsDo) Create(values ...*model.WinCodeRecords) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w winCodeRecordsDo) CreateInBatches(values []*model.WinCodeRecords, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w winCodeRecordsDo) Save(values ...*model.WinCodeRecords) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w winCodeRecordsDo) First() (*model.WinCodeRecords, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinCodeRecords), nil
	}
}

func (w winCodeRecordsDo) Take() (*model.WinCodeRecords, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinCodeRecords), nil
	}
}

func (w winCodeRecordsDo) Last() (*model.WinCodeRecords, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinCodeRecords), nil
	}
}

func (w winCodeRecordsDo) Find() ([]*model.WinCodeRecords, error) {
	result, err := w.DO.Find()
	return result.([]*model.WinCodeRecords), err
}

func (w winCodeRecordsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WinCodeRecords, err error) {
	buf := make([]*model.WinCodeRecords, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w winCodeRecordsDo) FindInBatches(result *[]*model.WinCodeRecords, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w winCodeRecordsDo) Attrs(attrs ...field.AssignExpr) IWinCodeRecordsDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w winCodeRecordsDo) Assign(attrs ...field.AssignExpr) IWinCodeRecordsDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w winCodeRecordsDo) Joins(fields ...field.RelationField) IWinCodeRecordsDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w winCodeRecordsDo) Preload(fields ...field.RelationField) IWinCodeRecordsDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w winCodeRecordsDo) FirstOrInit() (*model.WinCodeRecords, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinCodeRecords), nil
	}
}

func (w winCodeRecordsDo) FirstOrCreate() (*model.WinCodeRecords, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinCodeRecords), nil
	}
}

func (w winCodeRecordsDo) FindByPage(offset int, limit int) (result []*model.WinCodeRecords, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w winCodeRecordsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w winCodeRecordsDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w winCodeRecordsDo) Delete(models ...*model.WinCodeRecords) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *winCodeRecordsDo) withDO(do gen.Dao) *winCodeRecordsDo {
	w.DO = *do.(*gen.DO)
	return w
}
