// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gzorm/common/zorm/model"
)

func newWinBetslips9(db *gorm.DB, opts ...gen.DOOption) winBetslips9 {
	_winBetslips9 := winBetslips9{}

	_winBetslips9.winBetslips9Do.UseDB(db, opts...)
	_winBetslips9.winBetslips9Do.UseModel(&model.WinBetslips9{})

	tableName := _winBetslips9.winBetslips9Do.TableName()
	_winBetslips9.ALL = field.NewAsterisk(tableName)
	_winBetslips9.ID = field.NewInt64(tableName, "id")
	_winBetslips9.RoundID = field.NewString(tableName, "round_id")
	_winBetslips9.TransactionID = field.NewString(tableName, "transaction_id")
	_winBetslips9.XbStatus = field.NewInt64(tableName, "xb_status")
	_winBetslips9.XbUID = field.NewInt64(tableName, "xb_uid")
	_winBetslips9.XbUsername = field.NewString(tableName, "xb_username")
	_winBetslips9.MerchantID = field.NewInt64(tableName, "merchant_id")
	_winBetslips9.XbProfit = field.NewField(tableName, "xb_profit")
	_winBetslips9.Stake = field.NewField(tableName, "stake")
	_winBetslips9.ValidStake = field.NewField(tableName, "valid_stake")
	_winBetslips9.Payout = field.NewField(tableName, "payout")
	_winBetslips9.CoinRefund = field.NewField(tableName, "coin_refund")
	_winBetslips9.CoinBefore = field.NewField(tableName, "coin_before")
	_winBetslips9.GameProviderSubtypeID = field.NewInt64(tableName, "game_provider_subtype_id")
	_winBetslips9.GameListID = field.NewInt64(tableName, "game_list_id")
	_winBetslips9.GamePagcorID = field.NewInt64(tableName, "game_pagcor_id")
	_winBetslips9.GameProviderID = field.NewInt64(tableName, "game_provider_id")
	_winBetslips9.AmountType = field.NewInt64(tableName, "amount_type")
	_winBetslips9.DtStarted = field.NewInt64(tableName, "dt_started")
	_winBetslips9.DtCompleted = field.NewInt64(tableName, "dt_completed")
	_winBetslips9.WinTransactionID = field.NewString(tableName, "win_transaction_id")
	_winBetslips9.CreateTimeStr = field.NewString(tableName, "create_time_str")
	_winBetslips9.CreatedAt = field.NewInt64(tableName, "created_at")
	_winBetslips9.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_winBetslips9.GameTypeID = field.NewInt64(tableName, "game_type_id")

	_winBetslips9.fillFieldMap()

	return _winBetslips9
}

type winBetslips9 struct {
	winBetslips9Do

	ALL                   field.Asterisk
	ID                    field.Int64  // 主键
	RoundID               field.String // 回合id
	TransactionID         field.String // 注单号 对应三方拉单transaction_id
	XbStatus              field.Int64  // 注单状态 1:待开彩  2:完成  3: 退款
	XbUID                 field.Int64  // 对应user表id
	XbUsername            field.String // 对应user表username
	MerchantID            field.Int64  // 商户id
	XbProfit              field.Field  // 盈亏金额
	Stake                 field.Field  // 投注
	ValidStake            field.Field  // 有效投注金额
	Payout                field.Field  // 派彩
	CoinRefund            field.Field  // 退款金额
	CoinBefore            field.Field  // 投注前金额
	GameProviderSubtypeID field.Int64  // 游戏id对应game_provider_subtype表id
	GameListID            field.Int64  // 游戏id对应game_list表id
	GamePagcorID          field.Int64  // pagcor分组id
	GameProviderID        field.Int64  // 游戏供应商id
	AmountType            field.Int64  // 投注方式 1:现金，2:奖金 3:免费旋转 4:活动免费旋转
	DtStarted             field.Int64  // 游戏开始时间
	DtCompleted           field.Int64  // 游戏结束时间
	WinTransactionID      field.String // 开奖交易单号
	CreateTimeStr         field.String // 投注时间
	CreatedAt             field.Int64
	UpdatedAt             field.Int64
	GameTypeID            field.Int64 // 游戏分组id

	fieldMap map[string]field.Expr
}

func (w winBetslips9) Table(newTableName string) *winBetslips9 {
	w.winBetslips9Do.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w winBetslips9) As(alias string) *winBetslips9 {
	w.winBetslips9Do.DO = *(w.winBetslips9Do.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *winBetslips9) updateTableName(table string) *winBetslips9 {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.RoundID = field.NewString(table, "round_id")
	w.TransactionID = field.NewString(table, "transaction_id")
	w.XbStatus = field.NewInt64(table, "xb_status")
	w.XbUID = field.NewInt64(table, "xb_uid")
	w.XbUsername = field.NewString(table, "xb_username")
	w.MerchantID = field.NewInt64(table, "merchant_id")
	w.XbProfit = field.NewField(table, "xb_profit")
	w.Stake = field.NewField(table, "stake")
	w.ValidStake = field.NewField(table, "valid_stake")
	w.Payout = field.NewField(table, "payout")
	w.CoinRefund = field.NewField(table, "coin_refund")
	w.CoinBefore = field.NewField(table, "coin_before")
	w.GameProviderSubtypeID = field.NewInt64(table, "game_provider_subtype_id")
	w.GameListID = field.NewInt64(table, "game_list_id")
	w.GamePagcorID = field.NewInt64(table, "game_pagcor_id")
	w.GameProviderID = field.NewInt64(table, "game_provider_id")
	w.AmountType = field.NewInt64(table, "amount_type")
	w.DtStarted = field.NewInt64(table, "dt_started")
	w.DtCompleted = field.NewInt64(table, "dt_completed")
	w.WinTransactionID = field.NewString(table, "win_transaction_id")
	w.CreateTimeStr = field.NewString(table, "create_time_str")
	w.CreatedAt = field.NewInt64(table, "created_at")
	w.UpdatedAt = field.NewInt64(table, "updated_at")
	w.GameTypeID = field.NewInt64(table, "game_type_id")

	w.fillFieldMap()

	return w
}

func (w *winBetslips9) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *winBetslips9) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 25)
	w.fieldMap["id"] = w.ID
	w.fieldMap["round_id"] = w.RoundID
	w.fieldMap["transaction_id"] = w.TransactionID
	w.fieldMap["xb_status"] = w.XbStatus
	w.fieldMap["xb_uid"] = w.XbUID
	w.fieldMap["xb_username"] = w.XbUsername
	w.fieldMap["merchant_id"] = w.MerchantID
	w.fieldMap["xb_profit"] = w.XbProfit
	w.fieldMap["stake"] = w.Stake
	w.fieldMap["valid_stake"] = w.ValidStake
	w.fieldMap["payout"] = w.Payout
	w.fieldMap["coin_refund"] = w.CoinRefund
	w.fieldMap["coin_before"] = w.CoinBefore
	w.fieldMap["game_provider_subtype_id"] = w.GameProviderSubtypeID
	w.fieldMap["game_list_id"] = w.GameListID
	w.fieldMap["game_pagcor_id"] = w.GamePagcorID
	w.fieldMap["game_provider_id"] = w.GameProviderID
	w.fieldMap["amount_type"] = w.AmountType
	w.fieldMap["dt_started"] = w.DtStarted
	w.fieldMap["dt_completed"] = w.DtCompleted
	w.fieldMap["win_transaction_id"] = w.WinTransactionID
	w.fieldMap["create_time_str"] = w.CreateTimeStr
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
	w.fieldMap["game_type_id"] = w.GameTypeID
}

func (w winBetslips9) clone(db *gorm.DB) winBetslips9 {
	w.winBetslips9Do.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w winBetslips9) replaceDB(db *gorm.DB) winBetslips9 {
	w.winBetslips9Do.ReplaceDB(db)
	return w
}

type winBetslips9Do struct{ gen.DO }

type IWinBetslips9Do interface {
	gen.SubQuery
	Debug() IWinBetslips9Do
	WithContext(ctx context.Context) IWinBetslips9Do
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWinBetslips9Do
	WriteDB() IWinBetslips9Do
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWinBetslips9Do
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWinBetslips9Do
	Not(conds ...gen.Condition) IWinBetslips9Do
	Or(conds ...gen.Condition) IWinBetslips9Do
	Select(conds ...field.Expr) IWinBetslips9Do
	Where(conds ...gen.Condition) IWinBetslips9Do
	Order(conds ...field.Expr) IWinBetslips9Do
	Distinct(cols ...field.Expr) IWinBetslips9Do
	Omit(cols ...field.Expr) IWinBetslips9Do
	Join(table schema.Tabler, on ...field.Expr) IWinBetslips9Do
	LeftJoin(table schema.Tabler, on ...field.Expr) IWinBetslips9Do
	RightJoin(table schema.Tabler, on ...field.Expr) IWinBetslips9Do
	Group(cols ...field.Expr) IWinBetslips9Do
	Having(conds ...gen.Condition) IWinBetslips9Do
	Limit(limit int) IWinBetslips9Do
	Offset(offset int) IWinBetslips9Do
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWinBetslips9Do
	Unscoped() IWinBetslips9Do
	Create(values ...*model.WinBetslips9) error
	CreateInBatches(values []*model.WinBetslips9, batchSize int) error
	Save(values ...*model.WinBetslips9) error
	First() (*model.WinBetslips9, error)
	Take() (*model.WinBetslips9, error)
	Last() (*model.WinBetslips9, error)
	Find() ([]*model.WinBetslips9, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WinBetslips9, err error)
	FindInBatches(result *[]*model.WinBetslips9, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WinBetslips9) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWinBetslips9Do
	Assign(attrs ...field.AssignExpr) IWinBetslips9Do
	Joins(fields ...field.RelationField) IWinBetslips9Do
	Preload(fields ...field.RelationField) IWinBetslips9Do
	FirstOrInit() (*model.WinBetslips9, error)
	FirstOrCreate() (*model.WinBetslips9, error)
	FindByPage(offset int, limit int) (result []*model.WinBetslips9, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWinBetslips9Do
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w winBetslips9Do) Debug() IWinBetslips9Do {
	return w.withDO(w.DO.Debug())
}

func (w winBetslips9Do) WithContext(ctx context.Context) IWinBetslips9Do {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w winBetslips9Do) ReadDB() IWinBetslips9Do {
	return w.Clauses(dbresolver.Read)
}

func (w winBetslips9Do) WriteDB() IWinBetslips9Do {
	return w.Clauses(dbresolver.Write)
}

func (w winBetslips9Do) Session(config *gorm.Session) IWinBetslips9Do {
	return w.withDO(w.DO.Session(config))
}

func (w winBetslips9Do) Clauses(conds ...clause.Expression) IWinBetslips9Do {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w winBetslips9Do) Returning(value interface{}, columns ...string) IWinBetslips9Do {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w winBetslips9Do) Not(conds ...gen.Condition) IWinBetslips9Do {
	return w.withDO(w.DO.Not(conds...))
}

func (w winBetslips9Do) Or(conds ...gen.Condition) IWinBetslips9Do {
	return w.withDO(w.DO.Or(conds...))
}

func (w winBetslips9Do) Select(conds ...field.Expr) IWinBetslips9Do {
	return w.withDO(w.DO.Select(conds...))
}

func (w winBetslips9Do) Where(conds ...gen.Condition) IWinBetslips9Do {
	return w.withDO(w.DO.Where(conds...))
}

func (w winBetslips9Do) Order(conds ...field.Expr) IWinBetslips9Do {
	return w.withDO(w.DO.Order(conds...))
}

func (w winBetslips9Do) Distinct(cols ...field.Expr) IWinBetslips9Do {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w winBetslips9Do) Omit(cols ...field.Expr) IWinBetslips9Do {
	return w.withDO(w.DO.Omit(cols...))
}

func (w winBetslips9Do) Join(table schema.Tabler, on ...field.Expr) IWinBetslips9Do {
	return w.withDO(w.DO.Join(table, on...))
}

func (w winBetslips9Do) LeftJoin(table schema.Tabler, on ...field.Expr) IWinBetslips9Do {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w winBetslips9Do) RightJoin(table schema.Tabler, on ...field.Expr) IWinBetslips9Do {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w winBetslips9Do) Group(cols ...field.Expr) IWinBetslips9Do {
	return w.withDO(w.DO.Group(cols...))
}

func (w winBetslips9Do) Having(conds ...gen.Condition) IWinBetslips9Do {
	return w.withDO(w.DO.Having(conds...))
}

func (w winBetslips9Do) Limit(limit int) IWinBetslips9Do {
	return w.withDO(w.DO.Limit(limit))
}

func (w winBetslips9Do) Offset(offset int) IWinBetslips9Do {
	return w.withDO(w.DO.Offset(offset))
}

func (w winBetslips9Do) Scopes(funcs ...func(gen.Dao) gen.Dao) IWinBetslips9Do {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w winBetslips9Do) Unscoped() IWinBetslips9Do {
	return w.withDO(w.DO.Unscoped())
}

func (w winBetslips9Do) Create(values ...*model.WinBetslips9) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w winBetslips9Do) CreateInBatches(values []*model.WinBetslips9, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w winBetslips9Do) Save(values ...*model.WinBetslips9) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w winBetslips9Do) First() (*model.WinBetslips9, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinBetslips9), nil
	}
}

func (w winBetslips9Do) Take() (*model.WinBetslips9, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinBetslips9), nil
	}
}

func (w winBetslips9Do) Last() (*model.WinBetslips9, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinBetslips9), nil
	}
}

func (w winBetslips9Do) Find() ([]*model.WinBetslips9, error) {
	result, err := w.DO.Find()
	return result.([]*model.WinBetslips9), err
}

func (w winBetslips9Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WinBetslips9, err error) {
	buf := make([]*model.WinBetslips9, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w winBetslips9Do) FindInBatches(result *[]*model.WinBetslips9, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w winBetslips9Do) Attrs(attrs ...field.AssignExpr) IWinBetslips9Do {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w winBetslips9Do) Assign(attrs ...field.AssignExpr) IWinBetslips9Do {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w winBetslips9Do) Joins(fields ...field.RelationField) IWinBetslips9Do {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w winBetslips9Do) Preload(fields ...field.RelationField) IWinBetslips9Do {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w winBetslips9Do) FirstOrInit() (*model.WinBetslips9, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinBetslips9), nil
	}
}

func (w winBetslips9Do) FirstOrCreate() (*model.WinBetslips9, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinBetslips9), nil
	}
}

func (w winBetslips9Do) FindByPage(offset int, limit int) (result []*model.WinBetslips9, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w winBetslips9Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w winBetslips9Do) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w winBetslips9Do) Delete(models ...*model.WinBetslips9) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *winBetslips9Do) withDO(do gen.Dao) *winBetslips9Do {
	w.DO = *do.(*gen.DO)
	return w
}
