// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gzorm/commons/zorm/model"
)

func newWinLuckyUserDailyStat(db *gorm.DB, opts ...gen.DOOption) winLuckyUserDailyStat {
	_winLuckyUserDailyStat := winLuckyUserDailyStat{}

	_winLuckyUserDailyStat.winLuckyUserDailyStatDo.UseDB(db, opts...)
	_winLuckyUserDailyStat.winLuckyUserDailyStatDo.UseModel(&model.WinLuckyUserDailyStat{})

	tableName := _winLuckyUserDailyStat.winLuckyUserDailyStatDo.TableName()
	_winLuckyUserDailyStat.ALL = field.NewAsterisk(tableName)
	_winLuckyUserDailyStat.ID = field.NewInt64(tableName, "id")
	_winLuckyUserDailyStat.DrawConfigID = field.NewInt64(tableName, "draw_config_id")
	_winLuckyUserDailyStat.DrawDate = field.NewString(tableName, "draw_date")
	_winLuckyUserDailyStat.UID = field.NewInt64(tableName, "uid")
	_winLuckyUserDailyStat.Username = field.NewString(tableName, "username")
	_winLuckyUserDailyStat.Currency = field.NewString(tableName, "currency")
	_winLuckyUserDailyStat.RiskFlag = field.NewInt64(tableName, "risk_flag")
	_winLuckyUserDailyStat.BetCount = field.NewInt64(tableName, "bet_count")
	_winLuckyUserDailyStat.BetAmount = field.NewField(tableName, "bet_amount")
	_winLuckyUserDailyStat.WinCount = field.NewInt64(tableName, "win_count")
	_winLuckyUserDailyStat.WinAmount = field.NewField(tableName, "win_amount")
	_winLuckyUserDailyStat.ClaimCount = field.NewInt64(tableName, "claim_count")
	_winLuckyUserDailyStat.ClaimAmount = field.NewField(tableName, "claim_amount")
	_winLuckyUserDailyStat.LastBetAt = field.NewInt64(tableName, "last_bet_at")
	_winLuckyUserDailyStat.LastWinAt = field.NewInt64(tableName, "last_win_at")
	_winLuckyUserDailyStat.LastClaimAt = field.NewInt64(tableName, "last_claim_at")
	_winLuckyUserDailyStat.CreatedAt = field.NewInt64(tableName, "created_at")
	_winLuckyUserDailyStat.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_winLuckyUserDailyStat.fillFieldMap()

	return _winLuckyUserDailyStat
}

// winLuckyUserDailyStat Lucky 用户每日统计表
type winLuckyUserDailyStat struct {
	winLuckyUserDailyStatDo

	ALL          field.Asterisk
	ID           field.Int64  // 主键ID
	DrawConfigID field.Int64  // 活动主配置ID
	DrawDate     field.String // 统计日期 YYYY-MM-DD
	UID          field.Int64  // 用户ID
	Username     field.String // 用户名
	Currency     field.String // 币种
	RiskFlag     field.Int64  // 风控标记 0正常 1可疑
	BetCount     field.Int64  // 下注次数
	BetAmount    field.Field  // 下注总额
	WinCount     field.Int64  // 中奖次数
	WinAmount    field.Field  // 中奖总额
	ClaimCount   field.Int64  // 领取次数
	ClaimAmount  field.Field  // 领取总额
	LastBetAt    field.Int64  // 最后下注时间
	LastWinAt    field.Int64  // 最后中奖时间
	LastClaimAt  field.Int64  // 最后领取时间
	CreatedAt    field.Int64  // 创建时间
	UpdatedAt    field.Int64  // 更新时间

	fieldMap map[string]field.Expr
}

func (w winLuckyUserDailyStat) Table(newTableName string) *winLuckyUserDailyStat {
	w.winLuckyUserDailyStatDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w winLuckyUserDailyStat) As(alias string) *winLuckyUserDailyStat {
	w.winLuckyUserDailyStatDo.DO = *(w.winLuckyUserDailyStatDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *winLuckyUserDailyStat) updateTableName(table string) *winLuckyUserDailyStat {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.DrawConfigID = field.NewInt64(table, "draw_config_id")
	w.DrawDate = field.NewString(table, "draw_date")
	w.UID = field.NewInt64(table, "uid")
	w.Username = field.NewString(table, "username")
	w.Currency = field.NewString(table, "currency")
	w.RiskFlag = field.NewInt64(table, "risk_flag")
	w.BetCount = field.NewInt64(table, "bet_count")
	w.BetAmount = field.NewField(table, "bet_amount")
	w.WinCount = field.NewInt64(table, "win_count")
	w.WinAmount = field.NewField(table, "win_amount")
	w.ClaimCount = field.NewInt64(table, "claim_count")
	w.ClaimAmount = field.NewField(table, "claim_amount")
	w.LastBetAt = field.NewInt64(table, "last_bet_at")
	w.LastWinAt = field.NewInt64(table, "last_win_at")
	w.LastClaimAt = field.NewInt64(table, "last_claim_at")
	w.CreatedAt = field.NewInt64(table, "created_at")
	w.UpdatedAt = field.NewInt64(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *winLuckyUserDailyStat) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *winLuckyUserDailyStat) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 18)
	w.fieldMap["id"] = w.ID
	w.fieldMap["draw_config_id"] = w.DrawConfigID
	w.fieldMap["draw_date"] = w.DrawDate
	w.fieldMap["uid"] = w.UID
	w.fieldMap["username"] = w.Username
	w.fieldMap["currency"] = w.Currency
	w.fieldMap["risk_flag"] = w.RiskFlag
	w.fieldMap["bet_count"] = w.BetCount
	w.fieldMap["bet_amount"] = w.BetAmount
	w.fieldMap["win_count"] = w.WinCount
	w.fieldMap["win_amount"] = w.WinAmount
	w.fieldMap["claim_count"] = w.ClaimCount
	w.fieldMap["claim_amount"] = w.ClaimAmount
	w.fieldMap["last_bet_at"] = w.LastBetAt
	w.fieldMap["last_win_at"] = w.LastWinAt
	w.fieldMap["last_claim_at"] = w.LastClaimAt
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w winLuckyUserDailyStat) clone(db *gorm.DB) winLuckyUserDailyStat {
	w.winLuckyUserDailyStatDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w winLuckyUserDailyStat) replaceDB(db *gorm.DB) winLuckyUserDailyStat {
	w.winLuckyUserDailyStatDo.ReplaceDB(db)
	return w
}

type winLuckyUserDailyStatDo struct{ gen.DO }

type IWinLuckyUserDailyStatDo interface {
	gen.SubQuery
	Debug() IWinLuckyUserDailyStatDo
	WithContext(ctx context.Context) IWinLuckyUserDailyStatDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWinLuckyUserDailyStatDo
	WriteDB() IWinLuckyUserDailyStatDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWinLuckyUserDailyStatDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWinLuckyUserDailyStatDo
	Not(conds ...gen.Condition) IWinLuckyUserDailyStatDo
	Or(conds ...gen.Condition) IWinLuckyUserDailyStatDo
	Select(conds ...field.Expr) IWinLuckyUserDailyStatDo
	Where(conds ...gen.Condition) IWinLuckyUserDailyStatDo
	Order(conds ...field.Expr) IWinLuckyUserDailyStatDo
	Distinct(cols ...field.Expr) IWinLuckyUserDailyStatDo
	Omit(cols ...field.Expr) IWinLuckyUserDailyStatDo
	Join(table schema.Tabler, on ...field.Expr) IWinLuckyUserDailyStatDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWinLuckyUserDailyStatDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWinLuckyUserDailyStatDo
	Group(cols ...field.Expr) IWinLuckyUserDailyStatDo
	Having(conds ...gen.Condition) IWinLuckyUserDailyStatDo
	Limit(limit int) IWinLuckyUserDailyStatDo
	Offset(offset int) IWinLuckyUserDailyStatDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWinLuckyUserDailyStatDo
	Unscoped() IWinLuckyUserDailyStatDo
	Create(values ...*model.WinLuckyUserDailyStat) error
	CreateInBatches(values []*model.WinLuckyUserDailyStat, batchSize int) error
	Save(values ...*model.WinLuckyUserDailyStat) error
	First() (*model.WinLuckyUserDailyStat, error)
	Take() (*model.WinLuckyUserDailyStat, error)
	Last() (*model.WinLuckyUserDailyStat, error)
	Find() ([]*model.WinLuckyUserDailyStat, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WinLuckyUserDailyStat, err error)
	FindInBatches(result *[]*model.WinLuckyUserDailyStat, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WinLuckyUserDailyStat) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWinLuckyUserDailyStatDo
	Assign(attrs ...field.AssignExpr) IWinLuckyUserDailyStatDo
	Joins(fields ...field.RelationField) IWinLuckyUserDailyStatDo
	Preload(fields ...field.RelationField) IWinLuckyUserDailyStatDo
	FirstOrInit() (*model.WinLuckyUserDailyStat, error)
	FirstOrCreate() (*model.WinLuckyUserDailyStat, error)
	FindByPage(offset int, limit int) (result []*model.WinLuckyUserDailyStat, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWinLuckyUserDailyStatDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w winLuckyUserDailyStatDo) Debug() IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Debug())
}

func (w winLuckyUserDailyStatDo) WithContext(ctx context.Context) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w winLuckyUserDailyStatDo) ReadDB() IWinLuckyUserDailyStatDo {
	return w.Clauses(dbresolver.Read)
}

func (w winLuckyUserDailyStatDo) WriteDB() IWinLuckyUserDailyStatDo {
	return w.Clauses(dbresolver.Write)
}

func (w winLuckyUserDailyStatDo) Session(config *gorm.Session) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Session(config))
}

func (w winLuckyUserDailyStatDo) Clauses(conds ...clause.Expression) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w winLuckyUserDailyStatDo) Returning(value interface{}, columns ...string) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w winLuckyUserDailyStatDo) Not(conds ...gen.Condition) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w winLuckyUserDailyStatDo) Or(conds ...gen.Condition) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w winLuckyUserDailyStatDo) Select(conds ...field.Expr) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w winLuckyUserDailyStatDo) Where(conds ...gen.Condition) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w winLuckyUserDailyStatDo) Order(conds ...field.Expr) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w winLuckyUserDailyStatDo) Distinct(cols ...field.Expr) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w winLuckyUserDailyStatDo) Omit(cols ...field.Expr) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w winLuckyUserDailyStatDo) Join(table schema.Tabler, on ...field.Expr) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w winLuckyUserDailyStatDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w winLuckyUserDailyStatDo) RightJoin(table schema.Tabler, on ...field.Expr) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w winLuckyUserDailyStatDo) Group(cols ...field.Expr) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w winLuckyUserDailyStatDo) Having(conds ...gen.Condition) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w winLuckyUserDailyStatDo) Limit(limit int) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w winLuckyUserDailyStatDo) Offset(offset int) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w winLuckyUserDailyStatDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w winLuckyUserDailyStatDo) Unscoped() IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Unscoped())
}

func (w winLuckyUserDailyStatDo) Create(values ...*model.WinLuckyUserDailyStat) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w winLuckyUserDailyStatDo) CreateInBatches(values []*model.WinLuckyUserDailyStat, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w winLuckyUserDailyStatDo) Save(values ...*model.WinLuckyUserDailyStat) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w winLuckyUserDailyStatDo) First() (*model.WinLuckyUserDailyStat, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinLuckyUserDailyStat), nil
	}
}

func (w winLuckyUserDailyStatDo) Take() (*model.WinLuckyUserDailyStat, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinLuckyUserDailyStat), nil
	}
}

func (w winLuckyUserDailyStatDo) Last() (*model.WinLuckyUserDailyStat, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinLuckyUserDailyStat), nil
	}
}

func (w winLuckyUserDailyStatDo) Find() ([]*model.WinLuckyUserDailyStat, error) {
	result, err := w.DO.Find()
	return result.([]*model.WinLuckyUserDailyStat), err
}

func (w winLuckyUserDailyStatDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WinLuckyUserDailyStat, err error) {
	buf := make([]*model.WinLuckyUserDailyStat, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w winLuckyUserDailyStatDo) FindInBatches(result *[]*model.WinLuckyUserDailyStat, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w winLuckyUserDailyStatDo) Attrs(attrs ...field.AssignExpr) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w winLuckyUserDailyStatDo) Assign(attrs ...field.AssignExpr) IWinLuckyUserDailyStatDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w winLuckyUserDailyStatDo) Joins(fields ...field.RelationField) IWinLuckyUserDailyStatDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w winLuckyUserDailyStatDo) Preload(fields ...field.RelationField) IWinLuckyUserDailyStatDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w winLuckyUserDailyStatDo) FirstOrInit() (*model.WinLuckyUserDailyStat, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinLuckyUserDailyStat), nil
	}
}

func (w winLuckyUserDailyStatDo) FirstOrCreate() (*model.WinLuckyUserDailyStat, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinLuckyUserDailyStat), nil
	}
}

func (w winLuckyUserDailyStatDo) FindByPage(offset int, limit int) (result []*model.WinLuckyUserDailyStat, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w winLuckyUserDailyStatDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w winLuckyUserDailyStatDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w winLuckyUserDailyStatDo) Delete(models ...*model.WinLuckyUserDailyStat) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *winLuckyUserDailyStatDo) withDO(do gen.Dao) *winLuckyUserDailyStatDo {
	w.DO = *do.(*gen.DO)
	return w
}
